---
title: "Chapter One: Discussion 0.1"
output: word_document
always_allow_html: true
bibliography: chapter-one.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE)
```

During 2019-2020 we used nest cameras to assess reproductive success and breeding season diet at goshawk nests in the BC south coast region. We supplemented dietary data from nest cameras with egested pellets and prey remains collected from goshawk territories. The prey species taken by goshawks in our study are broadly similar to those taken elsewhere in North America. However, unlike other parts of the Pacific Northwest, goshawk diet in this region was dominated by mammalian prey, specifically tree squirrels (*Tamiasciurus* spp.), and this genus had a significant effect on goshawk reproductive success.

Overall, goshawks in North America consume more mammals relative to goshawks in Europe [@rutz_population_2006]. In the Interior West and Northwest, the dominant goshawk prey species is almost always a mammal, often snowshoe hare (*Lepus americanus*) or another member of the family Leporidae. However, in the Pacific Northwest goshawk diet generally contains more birds than mammals and the key prey species is generally a species of grouse (subfamily Tetraoninae). This is commonly attributed to a lower abundance and diversity of mammal species in the temperate rainforests which dominate this region (citation).

In contrast, we found n% of goshawk diet was composed of mammalian prey, primarily squirrels of the genus *Tamiusciurus*. Douglas squirrel (*T. douglasii*) was the most widespread squirrel within out study area, although red squirrel (*T. hudsonicus*) was also present at one site located within the overlap of the two species' ranges. Birds made up only n% of the diet and grouse made up a very small portion, n%. This surprising result is supported by a previous study on Vancouver Island, which likewise found red squirrel to be the dominant prey species, at x%. 

More comparison with other regions? Dig into differences with SE AK and WA?

Within our study area, a *transition zone* bridges the wet coastal forests and the arid interior, creating a narrow region where goshawk prey may be intermediate between the two ecoregions. Specifically, mammalian prey are suspected to be more abundant and diverse in the transition zone relative to the coastal zone. We found significant differences between the diet of birds in the transition and coastal zones. Birds in the transition zone consumed more corvids and other mammals (neither squirrel nor hare) but fewer thrushes, by count, than birds on the coast. While this supports the suggestion that goshawks in the transition zone have access to more mammalian prey and goshawks in the coastal zone are more dependent on birds, these prey groups made up a very small portion of the diet. The dominant prey, squirrels, were consumed equally between the two zones.

Discussion: diversity, overlap, etc

In some studies, the abundance of one or two dominant mammalian prey has been shown to be a significant driver of goshawk productivity. <!-- is there a similar example for grouse/birds in North America? --> Particularly strong examples come from northern latitudes, where goshawk productivity tracks cyclical variation in snowshoe hare abundance (McGowan 1975, Doyle & Smith 1994). Dietary niche breadth in these regions is low, which likely contributes to the observed variability of reproductive success. Greater dietary diversity may reduce such fluctuations, as seen on the Kaibab Plateau in Arizona. Although rabbit and hare are the dominant prey species, productivity on the Kaibab is driven by the total abundance of prey and the only single species with a significant relationship to goshawk productivity is the red squirrel.

Similar to the Kaibab, we found a strong relationship between goshawk reproductive success and tree squirrels. Nests which received a greater proportion of their diet from squirrels fledged more young than those which received less. Tree squirrels have several characteristics which make them ideal goshawk prey, including their size, quick processing time, and diurnal activity patterns. Although we observed differences in diet between the coastal and transition zones, we did not observe any difference in the amount of squirrels consumed, nor did observe any difference in goshawk productivity. This supports the conclusion that squirrels have the greatest influence on reproductive success.

Again as in the Kaibab, goshawks in our study area also consumed a wide variety of prey, which could help buffer goshawk populations from swings in squirrel abundance. However, we found no relationship between diet diversity and productivity, which would be expected if this were the case. There are several possible explanations for this. Our data span only two breeding seasons, and it is possible that squirrel abundance remained stable and high for the duration of our study. Alternatively, the abundance of multiple prey species may fluctuate synchronously, negating the benefits of prey-switching. Which, if either, of these explanations is at play could be untangled using estimates of prey density. Unfortunately, we were not able to collect data on prey density due to time constraints and the challenges of accessing many of our sites. Incorporating prey density into future studies of goshawk diet would illuminate this final link between prey abundance, prey selection, and productivity.

Several sources of bias complicate our conclusions. Goshawks occasionally cache items near the nest for delivery at a later time; thus, a single prey item may be delivered to the nest multiple times, leading to double-counting. Some authors have attempted to compensate for this by visually matching partial items. However, we found the discrete photographs captured by our trail cameras, as opposed to the continuous videography more widely employed in other studies, made this kind of matching nearly impossible. We therefore made no attempt to account for caching and accept that this somewhat increases the uncertainty of our results. However, we feel the impact of caching is minimal, as other authors report low numbers of cached items (around 8%, citation). Furthermore, we believe using biomass rather than counts for most of our analyses further compensates for this issue. 

A further bias stems from the source of diet data. We used three sources of data on goshawk diet--egested pellets, prey remains, and nest cameras--and found significant differences between the results they produced. Cameras are widely considered one of the least biased methods for measuring diet at the nest. We therefore consider our results from the nest cameras to be the truest approximation of goshawk diet, although we acknowledge that cameras are not entirely free of bias. Compared to cameras, prey remains were the most biased, grossly overestimating the proportion of diet composed of avian prey. At this coarse scale, pellets were less biased, showing a similar ratio of avian to mammalian prey as cameras. However, when prey were divided into eight broad groups, pellets underestimated the proportion of diet composed of squirrels. Pooling data from pellets and remains did not cancel out the bias of either. Finally, pellets captured very few prey species while remains captured a large number of species, including several--primarily birds--not captured by cameras. These complex and contradictory results highlight the importance of clearly reporting the source of raptor diet data. Because each of these sources has been used in past diet studies, we believe there is value in reporting the results of each, for ease of comparison. However, we recommend future diet studies prioritize collecting data via cameras, either video or still, rather than physical specimens. 

Nest cameras are an effective way to measure prey delivered to the nest, but are clearly limited in that this is all they are able to measure. Cameras cannot capture prey consumed by adults, away from the nest, or by juveniles after they have begun to fledge. As a result, cameras capture an incomplete picture of breeding season diet and offer no insight into winter diet. This lack is especially troubling as males may hunt different prey for themselves than they do to deliver to the nest, and female diet during the winter is likely a major determinant of whether breeding will occur the following spring. In this pellets and remains may offer some advantage, as they can be found away from the nest and persist on the forest floor over time, offering a wider temporal and spatial window into goshawk diet. However, their utility may be limited by the biases discussed above.

We observed several instances of siblicide and predation recorded on the nest cameras. Siblicide is common in raptors but has rarely been observed in goshawks, likely to due to the relative paucity of studies which observe chick survival over time. While our observations are themselves unsurprising, they highlight the value of nest cameras for making observations of chick survival and behavior in difficult-to-study birds like the northern goshawk.

Link siblicide and predation to squirrels? Tie back to management--highlight importance of diet.