---
title: "chapter one (compiled) 0.2"
output: html_notebook
always_allow_html: true
bibliography: chapter-one.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE)
```
# Introduction

Effective wildlife conservation often requires understanding diet composition and its consequences for population demographics. Specialist predators selectively consume a narrow range of prey species regardless of their abundance, whereas generalists opportunistically consume a wider range and readily switch between species in response to changes in prey abundance [@steenhof_dietary_1988; @terraube_factors_2011]. Specialization increases foraging efficiency on the preferred prey at the potential cost of decreased reproductive success for the specialist when that prey is scarce [@newton_population_1998]. However, even in a generalist predator a single key prey species may be a major driver of reproductive success [@elmhagen_arctic_2000; @resanomayor_dietdemography_2016]. For at-risk predators, increasing the abundance of key prey species may be a useful conservation tool [@ferrer_near_2004;  @forsman_diets_2004; @resanomayor_dietdemography_2016].

<!-- Newton 1998: "Much depends on how varied the diet is, and whether alternate prey are available when favoured prey are scarce. The mroe diverse the diet, the less the chance of all prey-species being scarce at the same time. Raptors that have fairly stable food-supplies show some of the most extreme stability in breeding population recorded in birds.... Moreover, the same species may fluctuate numerically in one region, but not another, depending on the stability of the local prey supply." -->

<!-- Elmhagen et al. 2000: "The arctic fox thus manages to combine an opportunistic feeding strategy which ensures survival in a low productivity habitat, with a remarkable ability to exploit lemming peaks for a large reproductive output." -->

<!--Resano-Major et al 2016: "We found that several key demographic parameters of an endangered raptor such as Bonelli’s eagle in western Europe are dependent on the consumption of preferred and alternative prey species and on diet diversity." -->

The northern goshawk (*Accipiter gentilis*) is a large forest-dwelling raptor with a Holarctic distribution. A generalist predator, the goshawk hunts a variety of small- and medium-sized mammals and birds, including squirrels, lagomorphs, grouse, corvids, and woodpeckers [@squires_northern_2020]. Despite this diverse diet, throughout much of the goshawk's range a single prey species or narrow suite of species has a strong effect on their demographics. In the Yukon, goshawks depend on snowshoe hare (*Lepus americanus*) and show strong variation in productivity, mortality, and space use in response to cyclical changes in hare abundance [@doyle_population_1994]. Goshawks in Scandinavia likewise rely heavily on a single prey taxa, grouse (subfamily Tetraoninae), and show changes in productivity and occupancy based on annual grouse abundance [@tornberg_delayed_2005]. In contrast, goshawks in the American Southwest have a wide prey base, regularly taking some fourteen different species [@boal_northern_1994]. Fluctuations in goshawk productivity in this region are small and driven by total prey abundance, though the most influential single species is red squirrel (*Tamiasciurus hudsonicus*) [@salafsky_reproductive_2007]. These examples suggest the identity, and influence of a key prey species on reproductive success in such an adaptable predator may be specific to each region.

Like many raptors, goshawk populations appear to be limited primarily by nest site availability and prey abundance [@reynolds_review_2006; @rutz_population_2006]. <!--In addition to the multiple studies which have documented the link between prey abundance and goshawk productivity, supplemental feeding has been shown to decrease nest predation, suggesting low prey abundance increases the risk of reproductive failure [@ward_effects_1996]. -->However, measuring prey abundance is not always possible due to logistic constraints. Further, abundance estimates may be misleading when prey abundance does not reflect prey availability [@janes_influences_1984; @beier_forest_1997] or when predators show a functional rather than numeric response to changes in prey abundance [@dupuy_numerical_2009]. In these cases, dietary variables such as composition or diversity may offer insight into factors limiting reproductive success.

In British Columbia, the coastal population of northern goshawks is the subject of federal and provincial management which focuses on the protection of breeding habitat to increase nest site availability [@cosewic_cosewic_2013]. This strategy is due, in part, to a relative paucity of knowledge regarding goshawk foraging behavior and habitat. The diet of this population appears to be variable, with hawks on Vancouver Island, British Columbia, consuming primarily red squirrels [@ethier_breeding_1999], whereas hawks in the nearby regions of southeast Alaska [@lewis_northern_2006] and western Washington [@bloxton_prey_2002] take mostly medium and large birds. Even within British Columbia, a gradient of forest types from wet coastal to dry interior may produce dietary variation at intermediate scales [@ngrt_recovery_2008]. Detailed, local information regarding the effect of goshawk diet on reproductive success within coastal British Columbia is lacking, hindering the inclusion of limiting factors beyond nest site availability into management plans for this population.

Here we describe the breeding season diet of northern goshawks in coastal British Columbia over a two-year period. We assess whether goshawk diet differs within this region between the wetter *coastal* zone and the drier *transition* zone. We further evaluate whether dietary variables (composition, diversity) influence goshawk reproductive success.

# Methods

## Study Area and Species

In North America, the northern goshawk ranges from boreal forests of the Yukon south to high-elevation forests of Arizona and New Mexico. Two subspecies are currently recognized: the widespread *atricapillus* and the limited *laingi* [@squires_northern_2020].<!-- COSEWIC says 3 subssp but never even names A. g. apache --> The *laingi* subspecies was first described on the Haida Gwaii archipelago in British Columbia and is generally smaller in size and darker in plumage than the *atricapillus* subspecies found elsewhere on the continent [@taverner_variation_1940]. The range of this subspecies is limited to the west coast of North America from southeast Alaska through mainland British Columbia and Vancouver Island, possibly as far south as Washington's Olympic Peninsula [@cosewic_cosewic_2013]. *A. g. laingi* is considered a species at risk in British Columbia by both the federal and provincial governments due to significant loss of habitat resulting from industrial timber harvest [@ngrt_recovery_2008; @cosewic_cosewic_2013].

<!--Squires et al. 2020: "Accipiter g. atricapillus (Wilson) 1812, breeds throughout North America, except in areas occupied by other subspecies. Vagrants to the British Isles have been noted Oct-Feb (Cramp and Simmons 1980a). Compared to other subspecies, atricapillus is distinguished by its broad supercilium and deep-red iris. A. g. laingi (Taverner) Taverner 1940, breeds on Queen Charlotte Is. and Vancouver I. and is characterized by its darker coloration overall, black of crown extending to interscapulars, sootier gray ventrally, especially across the breast, and smaller size (wing length [convex distance] adult males: 325.2 mm ± 2.2 SE (n = 24; Johnson 1989b). Distribution of laingi extends from Vancouver I. northward through insular British Columbia, insular (Alexander Archipelago) and coastal mainland Alaska north to Icy Strait and Lynn Canal (Webster 1988, Titus et al. 1994, Iverson et al. 1996a). A. g. apache (van Rossem) Van Rossem 1938a, resident from s. Arizona south locally in mountains of Mexico to Jalisco is darker dorsally, almost blackish, and larger. Recognition of this race has been debated, but it is recognized by Phillips et al. (Phillips et al. 1964a), Wattel (Wattel 1973), Hubbard (Hubbard 1992), and Whaley and White (Whaley and White 1994)." -->

We studied goshawks in the Sunshine Coast and Lower Mainland regions of the south coast of British Columbia. This population of goshawks is currently classified as *A. g. laingi*, though recent genetic evidence suggests *laingi* is strictly limited to Haida Gwaii and may lead this population to be reclassified [@geraldes_population_2018]. The south coast region is primarily temperate rainforest dominated by Douglas-fir (*Pseudotsuga menziesii*), western redcedar (*Thuja plicata*), and western hemlock (*Tsuga heterophylla*) [@meidinger_ecosystems_1991]. Within this region, goshawk managers have delineated a *transition zone* comprised of low-elevation valleys connecting the wet forests of the *coast zone* with the dry interior forests east of the Coast Mountains. This transition zone likely represents an area of overlap between the coastal *laingi* population and the interior *atricapillus* population. 

<!-- NGRT 2008: "The precise range boundaries are unclear and there is likely some overlap between A. gentilis laingi and A. gentilis atricapillus where coastal forests transition to interior forests."

"Within this range map the recovery team identified a zone where coastal habitat types transition to interior habitat types, which reflects an area where differences between A. gentilis laingi and A. gentilis atricapillus are likely less clear." -->

## Data Collection

We assessed goshawk diet in 2019 and 2020 through a combination of egested pellets, prey remains, and nest cameras. We identified prey from pellets and remains collected from n nests and from photographs taken at n nests across the coastal and transition zones. Goshawk nests were located as part of long-term monitoring conducted by the British Columbia Ministry of Forests, Lands, Natural Resource Operations and Rural Development (FLNRO) (for detailed survey methodology see @mcclaren_northern_2005). 

Prey remains and egested pellets were collected from n sites (2019 *n* = n, 2020 *n* = n) with active nests. N sites had collections from both years. Prey remains and pellets were gathered from beneath active nests, from within nests after juveniles had fledged, and from plucking posts located within the site. All prey remains and all pellets from a single collection location (i.e., one nest or one plucking post) were combined into a single sample for each visit to that location. 

At a subset of these sites (2019 *n* = 6, 2020 *n* = n), cameras were installed at nests to record prey delivered to chicks. N nests had cameras installed in both years. Nest cameras are an effective and relatively unbiased method of measuring avian diet [@garcia-salgado_evaluation_2015 ;@harrison_using_2019]. However, cameras may overestimate prey deliveries because goshawks are known to cache prey items for re-delivery to the nest at a later time, creating a risk of double-counting items. Due to the discrete nature of our data, we were unable to differentiate cached and re-delivered items from new items and did not attempt to account for caching in our analysis.

Nest cameras were digital trail cameras (Reconyx brand, UltraFire and HyperFire models) mounted 2-5 meters distant from and slightly above the nest, usually in an adjacent tree. Cameras in 2019 were programmed to take three photos one second apart when triggered by motion, and an additional one photo every thirty minutes. In 2020, cameras were programmed to take five photos one second apart when triggered by motion, and an additional one photo every twenty minutes. Installation took place during the early nestling phase (between x June and x June) and cameras were left in place until after juveniles dispersed in the fall. Camera site selection was not random but rather constrained by topography, access, and timing of discovery.

Breeding chronology was not available for most sites. At sites with cameras, chicks were aged from photos taken shortly after camera installation using a pictorial guide [@boal_photographic_1994]. Productivity was defined as the number of chicks to reach 32 days age [@boal_photographic_1994, @mcclaren_northern_2002]. 

<!-- Steenhof & Kochert 1982 define fledging  success as number of young to reach 80% of the average age when young leave the nest. Boal 1994 states this is 32 days for NOGO, and this is the definition McClaren 2002 uses. -->

## Diet Quantification

We reconstructed prey from pellets and prey remains following a modification of the protocol used by @lewis_comparison_2004. Within each sample, prey remains were identified to the lowest possible taxonomic category and the minimum number of individuals counted (i.e. 3 hare femurs = 2 *Lepus americanus*). Intact pellets and broken but reassembled pellets were analyzed individually within each sample, while fragmented pellets were combined within each sample. Pellets were dissected and feathers, fur, and hard parts (bones, teeth, claws) were identified to the lowest taxonomic level. We counted the minimum number of individuals represented within the pellet or pellet collection. Items were additionally categorized by size (small = sparrow- or vole-sized, medium = jay- or squirrel-sized, and large = grouse- or hare-sized).

Prey items identified to species were assigned mass using data from the literature. We assigned mass to mammal species from @nagorsen_identification_2002 and to birds from @billerman_birds_2020, using the geographically closest estimates and averaging the mass of males and females. When unable to differentiate between species within a single, relatively homogeneous genus (such as *Eutamias* or *Myotis*), we assigned mass by averaging the masses of all possible species, based on range maps. Red squirrels (*Tamiasciurus hudsonicus*) were present at a single site within out study area; when unable to distinguish between the two members of the genus *Tamiasciurus* we assigned the item to the more common *T. douglasii*. Unidentified items were assigned mass by averaging the masses of the identified species in that size category and taxonomic class. As very few items could be successfully aged, we did not include prey age in our analysis. 

Data from prey remains and egested pellets are known to be biased indices of diet. Some authors have found combining data from both sources to produce relatively unbiased results that can serve as a helpful supplement to camera data [@lewis_comparison_2004]. However, after testing for differences between pooled pellets-and-remains and camera data we found significant differences between these two sources. We therefore report results from pellets and pooled pellets-and-remains separately. We do not report results from prey remains alone, as diet composition estimates from prey remains are highly biased and rarely used in raptor diet studies.

Nest camera photos were reviewed and each new prey item delivered to the nest was recorded and identified to species when possible. When items could not be identified to species, they were identified to the lowest possible taxonomic level. Prey items identified from photos were assigned a size category and biomass by the same method used for remains and pellets. Partial items were assigned the average mass for that size category and taxonomic class. 

For the overall study area, we quantified goshawk diet in several ways using data from pellets, pooled pellets-and-remains, and nest cameras. We calculated the relative proportion of avian and mammalian biomass delivered to nests. We also calculated the relative proportion of biomass composed of tree squirrels (genus *Tamiasciurus*), which are known to be an important source of prey for goshawks in British Columbia [@ethier_breeding_1999]. For sites with nest cameras, we also quantified diet at the individual nest level, and further calculated diet diversity with Simpson's Diversity Index [@simpson_measurement_1949]<!-- actually read this--> and overlap between nests with Morisita's Index of Similarity [@krebs_ecological_1999], using counts of items identified to genus or better.

Sites were classified as either coastal or transition based on whether the site centroid fell within the transition zone defined by @ngrt_recovery_2008. We determined the site centroid by locating the central point between all known nests within each site. Using data from pellets, pooled pellets-and-remains, and nest cameras, we quantified the diet of each zone in the same manner as for the overall study area. 

## Statistical Analysis

For ease of comparison between coastal and transition zone sites, we simplified prey items identified from nest cameras, pellets, and pooled pellets-and-remains into eight broad categories: squirrels (genus *Tamiasciurus*), hares (genus *Lepus*), all other mammals, grouse (subfamily Tetraoninae), thrushes (family Turdidae), corvids (family Corvidae), all other birds, and unidentified items. We pooled all data within each source (cameras, pellets, and pellets-and-remains) and within each zone (coastal and transition) and tested for differences between the zones with a chi-squared test using proportional counts of items.

To determine the reproductive consequences of dietary variation, we examined how two aspects of diet, diet diversity and proportion of biomass composed of squirrel, influenced productivity. We used linear regressions in R [@R_2020] with productivity as the response variable and diet as the explanatory variable. Because productivity data were available only from sites with nest cameras and nest-level diet data from pellets and prey remains were sparse, we performed this analysis using only diet data from nest cameras.

# Results

## Goshawk Diet

We identified a total of 71 prey items from pellets collected at n sites. Of these, 48% could be identified to genus or better, and no item could not be identified at least to class. From pellets alone, only 4 unique prey species were identified. Another 68 items were identified from prey remains collected at n sites, of which 49% were identified to genus or better and only one could not be identified to class. From the combined pellets-and-remains sample a total of 18 unique prey species were identified.

The majority of the prey items identified from pellets were mammals (77% biomass, x% counts). Squirrels made up 53% of biomass, while other birds made up another 23%. The remainder was composed of other mammals (%) and thrushes (%). The combined pellets-and-remains sample showed a very different composition, with only 37% of the diet made up of mammals and the majority (61%) made up of birds. The most commonly identified prey group was other birds (53%), followed by squirrels (14%) and other mammals (7%).

We obtained 26577 photos from 6 nests during the 2019 breeding season and n photos from n nests during 2020. A total of n prey item deliveries were recorded (2019 *n* = n, 2020 *n* = n). Camera effectiveness varied between sites: an average of n items were recorded per site, but some sites had as few as n items and some as many as n. This variability was due to differences in camera placement and sensitivity settings. n% of deliveries were obscured from the camera during delivery and consumption and were entirely removed from the analysis. Of the remaining n visible items we were able to identify n to class and n to genus or better. Small and medium birds were disproportionately represented among items only identified to class, frequently arriving at the nest already plucked and decapitated.

We identified 16 different prey species on nest cameras. By biomass, mammals made up the largest proportion of prey (84%, mean = x, sd = x), which was driven by the overwhelming dominance of tree squirrels (*Tamiasciurus* spp.). Birds accounted for only 13% of biomass (mean = x, sd = x), and the remaining 3% could not be identified to class (mean = x, sd = x). The most commonly identified prey categories by biomass were squirrels (71%, mean = x, sd = x), other mammals (7%, mean = x, sd = x) and thrushes (1%, mean = x, sd = x). Based on items identified to genus or better, overall diet diversity for the study area was moderate (x = 0.53). Diet diversity of individual nests was highly variable (mean = 0.56, sd = n) and overlap between nests was low (mean = 0.26, sd = n).

## Difference between ecological regions

Nests in the transition zone (*n* = 4) received a slightly larger proportion of biomass from mammalian prey than did nests in the coastal zone (*n* = 2) (85% and 79%, respectively). However, the proportion of diet composed of squirrels was equally high in both the transition zone (70%) and coastal zone (73%). Diet diversity was slightly higher in the transition zone (0.58) than the coastal zone (0.40). Diet overlap between the two zones was also high (x).

A chi-squared test of pellet data alone did not show a significant difference between goshawk diet in the coastal and transition zones (df = df, X = 1.9778, p = 0.66). However, a chi-squared test of pooled pellet-and-remains data did show a significant difference (df = df, X = 12.656, p = 0.04), as did a test of the camera data (chi-squared = 19.725, p = 0.007).

## Productivity

We observed no nest abandonment following camera installation. One nest in 2019 failed 9 days after installation. The remaining n nests all fledged at least one chick. The unsuccessful 2019 nest failed after two chicks succumbed to siblicide and the third appeared to fledge prematurely. Siblicide was observed in two other nests, which lost one chick each. Successful nests fledged 1 (*n* = n), 2 (*n* = n), or 3 (*n* = n) chicks.

We found goshawk productivity was positively correlated with of the proportion of diet composed of squirrel biomass on goshawk productivity (*p* = 0.03, adjusted r^2^ = 0.64). However, goshawk productivity was not related to diet diversity (p = 0.16). There was also no significant difference in goshawk productivity between the coastal and transitional zones (p = 0.63).

# Discussion

During 2019-2020 breeding seasons we used nest cameras to assess reproductive success and diet at goshawk nests on the south coast of British Columbia. We supplemented dietary data from nest cameras with egested pellets and prey remains collected from goshawk territories. Goshawks in our study area consumed a wide range of prey species, consistent with the species' generalist foraging strategy. Despite this high dietary richness, dietary diversity was relatively low, due to the dominance of a single taxa: tree squirrels of the genus *Tamiasciurus*. We found the degree of dominance of this genus, rather than dietary diversity, drove goshawk reproductive success, indicating a specialist-like reliance on a single taxa.

Goshawks show a similar pattern of regional specialization in other portions of their range. In the interior west of North America, the key goshawk prey species is almost always a mammal, usually of the family Leporidae or Sciuridae [@boal_northern_1994; @doyle_population_1994; @destefano_ecology_2006; @miller_effects_2014]. However, in the coastal temperate rainforests of the Pacific Northwest, goshawk diet generally contains more birds than mammals and the key prey is usually a species of grouse (subfamily Tetraoninae) [@watson_prey_1998; @thraikill_diet_2000; @bloxton_prey_2002; @lewis_northern_2006]. Goshawks in coastal British Columbia might be expected to follow this pattern, yet on Vancouver Island goshawks consume primarily red squirrels (*T. hudsonicus*), with this single species making up x% of the diet [@ethier_breeding_1999]. Similarly, we found tree squirrels (*T. douglasii* and *T. hudsonicus*) to make up, on average, x% of goshawk diet on the mainland coast.

A likely explanation for this surprising result rises from the predictions of optimal foraging theory. Predators are expected to specialize on a preferred high-value prey while its abundance is high, and diversify to less preferred prey as abundance declines [@pyke_optimal_1977]<!--actually read this-->. Raptors are generally able to handle mammalian prey faster and more efficiently than avian prey [@slagsvold_prey_2007; @slagsvold_prey_2010]. Of the potential mammalian prey present within our study area, tree squirrels' numerical density and diurnal activity pattern make them one of the most abundant and available. However, densities of tree squirrels elsewhere in the Pacific Northwest are much lower than in coastal British Columbia [@carey_northern_1992; @carey_sciurids_1995; @ransome_population_2003; but see @smith_flying_2012]<!--should I really include this?-->, potentially forcing goshawks to diversify to lower-value grouse and other birds in these areas. The south coast of British Columbia and east coast of Vancouver Island lie within the rainshadow of Vancouver Island, making it slightly drier than elsewhere in the temperate rainforest zone [@meidinger_ecosystems_1991]. <!-- which is reflected in the patchy occurrence of tree species such as Garry's oak (*Quercus garryana*), arbutus (*Arbutus menziesii*), and pine (*Pinus sp.*).--> The unique climate of our study area may support an unusually high abundance of tree squirrels relative to other parts of the coastal Pacific Northwest, allowing goshawks to specialize on this high-value prey taxa.

Although goshawks in our study area consumed more than 16 different prey species, it was the degree of specialization on this single taxa which predicted goshawk productivity. Nests which received a greater proportion of their diet from tree squirrels fledged more chicks than those which received relatively more biomass from birds and other mammals. We observed a slight negative correlation between the proportion of diet composed of squirrel biomass <!--this isn't in methods/results, should it be? --> and diet diversity, although diversity had no significant effect on reproductive success. This suggests goshawks without access to abundant tree squirrels unsuccessfully attempted to compensate by switching to alternate prey species. Another explanation may be younger hawks lacked the experience to hunt tree squirrels regardless of squirrel abundance. Both possibilities indicate tree squirrels are one of the few taxa able to provide sufficient biomass to affect goshawk productivity. However, productivity is determined by more than fledging success alone, and additional factors such as clutch size and hatch success also play an important role [@ricklefs_components_1977]. Because we measured only fledging success we are unable, from the limited scope of our study, to untangle the mechanism behind this correlation.

<!-- Newton 1998: "Depending on the stage at which they occur, effects of food-shortages can be manifest through non-laying, small clutches, egg-desertion, poor chick growth and survival, and (in multi-brooded species), in reduced numbers of nesting attempts per season, as well as in loss of weight and and reduced survival prospects in adults." -->

Within our study area, low-elevation mountain valleys bridge the wet forests of the coast and the dry forests of the interior, creating a narrow region where coastal and interior goshawk populations may overlap [@ngrt_recovery_2008]. This transition zone provided us with a fortuitous opportunity to examine dietary variation over intermediate scales. Just as our study area is slightly drier than other regions of the coastal Pacific Northwest, the transition zone is slightly drier than the majority of our study area. <!--Other authors have speculated the dominance of avian prey in the diet of coastal Pacific Northwest goshawks is due to lower abundance or availability of mammalian prey in temperate rainforest ecosystems (Rutz et al 2006, McClaren et al 2015). -->We might therefore expect hawks in the transition zone to consume more or more variety of mammalian prey than hawks in the coastal zone. We did find a significant difference in diet between the transition and coastal zones, with hawks in the transition zone consuming a more diverse diet with a greater proportion of mammalian prey, but we found no difference in either the consumption of tree squirrels or in goshawk productivity. This similarity between ecological zones supports the conclusion that, although goshawks may opportunistically hunt prey species which are locally available, they specialize on a single high-value prey resource which strongly influences their reproductive success.

Several sources of bias complicate our conclusions, the greatest of which stems from the source of diet data. We used three sources of data to quantify goshawk diet--egested pellets, prey remains, and nest cameras--and found significant differences between the results they produced. Cameras are widely considered one of the least biased methods for measuring diet at the nest in raptors [@tornberg_assessing_2007; @garcia-salgado_evaluation_2015; @harrison_using_2019]. We therefore consider our results from the nest cameras to be the truest approximation of goshawk diet, although we acknowledge that cameras are not entirely free of bias. Compared to cameras, prey remains were the most biased, grossly overestimating the proportion of the diet composed of avian prey. For this reasons we did not analyze prey remains alone, but the avian bias carried into the pooled pellets-and-remains sample, which we did analyze. On the other hand, pellets allowed few prey items to be identified to species, while prey remains allowed the identification of a large number of species, including several--primarily birds--not captured by cameras. These complex and contradictory results highlight the importance of clearly reporting the source of raptor diet data. Because each of these sources has been used in past diet studies, we believe there is value in reporting the results of each for ease of comparison. However, we recommend future diet studies prioritize collecting data via cameras, either video or still images, rather than physical specimens. 

Our study answers several fundamental questions regarding the basic ecology of an at-risk population of northern goshawks, but many more remain unanswered. We were unable to collect data on prey abundance and so cannot draw any conclusions regarding goshawk prey selection. Furthermore, while nest cameras are an effective way to measure prey delivered to the nest, they cannot record prey consumed by adults away from the nest, prey consumed by juveniles after they have fledged, or prey consumed during the winter. As a result, we captured an incomplete picture of breeding season diet and have no insight into nonbreeding season diet. These limitations are not exclusive to our work: few studies have successfully combined prey abundance with both goshawk diet and reproductive success, and no North American study has comprehensively addressed goshawk diet away from the nest [@rutz_population_2006; @squires_northern_2006]. Filling these gaps represents an important direction for future studies of northern goshawks in British Columbia and throughout the species' range.

# Literature Cited