---
title: "Chapter One: Methods 0.4"
output: html_notebook
always_allow_html: true
bibliography: chapter-one.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE)
```

### Study Area and Species

In North America, the northern goshawk ranges from boreal forests of the Yukon south to high-elevation forests of Arizona and New Mexico. Two subspecies are currently recognized: the widespread *atricapillus* and the limited *laingi* (Birds of North America). The *laingi* subspecies was first described on the Haida Gwaii archipelago in British Columbia and is generally smaller in size and darker in plumage than the *atricapillus* subspecies found elsewhere on the continent (Taverner 1940). Its range, as defined by morphological characteristics and habitat modeling, is limited to the west coast of North America from southeast Alaska through mainland British Columbia and Vancouver Island, possibly as far south as Washington's Olympic Peninsula (COSEWIC 2013). *A. g. laingi* is considered a species at risk in British Columbia by both the federal and provincial governments due to significant loss of habitat resulting from industrial timber harvest (NGRT 2008, Parks Canada 2017).

We studied goshawks in the Sunshine Coast and Lower Mainland regions of the south coast of British Columbia. This population of goshawks is currently classified as *A. g. laingi*, though recent genetic evidence suggests *laingi* is strictly limited to Haida Gwaii and may lead to future reclassification of the coastal mainland population (Geraldes et al 2018). The south coast region is primarily temperate rainforest dominated by Douglas-fir (*Pseudotsuga menziesii*), western redcedar (*Thuja plicata*), and western hemlock (*Tsuga heterophylla*) (Meidinger & Pojar 1991). <!-- Summers are cool (mean temp) and winters are mild and wet (mean temp, mean precip). Forests are naturally fragmented by mountain ranges and coastal fjords, and artificially fragmented by human development and natural resource extraction. Industrial timber harvest has created a patchwork of differently aged forest stands, ranging from recent clearcuts to old growth over two hundred years old.--> Within this region, goshawk managers have delineated a *transition zone* comprised of low-elevation valleys connecting the wet forests of the *coast zone* with the dry interior forests east of the Coast Mountains. Goshawks in this transition zone may have morphological characteristics and habitat requirements intermediate between the coastal *laingi* population and the interior *atricapillus* population. As a result, this zone is of particular interest to goshawk managers (NGRT 2008).

### Data Collection

We assessed goshawk diet in 2019 and 2020 through a combination of egested pellets, prey remains, and nest cameras. We identified prey from pellets and remains collected from n nests and from photographs taken at n nests across the coastal and transition zones. Goshawk nests were located as part of long-term monitoring conducted by the British Columbia Ministry of Forests, Lands, Natural Resource Operations and Rural Development (FLNRO) (for detailed survey methodology see McClaren 2005). 

Prey remains and egested pellets were collected from n sites (2019 *n* = n, 2020 *n* = n) with active nests. N sites had collections from both years. Prey remains and pellets were gathered from beneath active nests, from within nests after juveniles had fledged, and from plucking posts located within the site. All prey remains and all pellets from a single collection location (i.e., one nest or one plucking post) were combined into a single sample for each visit to that location. 

At a subset of these sites (2019 *n* = 6, 2020 *n* = n), cameras were installed at nests to record prey delivered to the chicks. N nests had cameras installed in both years. Nest cameras are an effective and relatively unbiased method of measuring avian diet (Garcia-Salgado 2015, Harrison et al 2019). However, cameras may overestimate prey deliveries because goshawks are known to cache prey items for re-delivery to the nest at a later time, creating a risk of double-counting items. Due to the discrete nature of our data, we were unable to differentiate cached and re-delivered items from new items and did not attempt to account for caching in our analysis.

Nest cameras were digital trail cameras (Reconyx brand, UltraFire and HyperFire models) mounted 2-5 meters distant from and slightly above the nest, usually in an adjacent tree. Cameras in 2019 were programmed to take three photos one second apart when triggered by motion, and an additional one photo every thirty minutes. In 2020, cameras were programmed to take five photos one second apart when triggered by motion, and an additional one photo every twenty minutes. Installation took place during the early nestling phase (between x June and x June) and cameras were left in place until after juveniles dispersed in the fall. Camera site selection was not random but rather constrained by topography, access, and timing of discovery.

Breeding chronology was not available for most sites. At sites with cameras, chicks were aged from photos taken shortly after camera installation using a pictorial guide (Boal 1994). <!--Hatch date and lay date were calculated from this date using known breeding chronology (Boal 1994, McClaren et al. 2015). --> Productivity was defined as the number of chicks to reach 32 days age (McClaren et al 2002). 

### Diet Quantification

We reconstructed prey from pellets and prey remains following a modification of Lewis et al. (2004). Within each sample, prey remains were identified to the lowest possible taxonomic category and the minimum number of individuals counted (i.e. 3 hare femurs = 2 *Lepus americanus*). Intact pellets and broken but reassembled pellets were analyzed individually within each sample, while fragmented pellets were combined within each sample. Pellets were dissected and feathers, fur, and hard parts (bones, teeth, claws) were identified to the lowest taxonomic level. We counted the minimum number of individuals represented within the pellet or pellet collection. Items were additionally categorized by size (small = sparrow- or vole-sized, medium = jay- or squirrel-sized, and large = grouse- or hare-sized).

Prey items identified to species were assigned mass using data from the literature. We assigned mass to mammal species from Nagorsen (2002) and to birds from Birds of World (2020), using the geographically closest estimates and averaging the mass of males and females. When unable to differentiate between species within a single, relatively homogeneous genus (such as *Eutamias* or *Myotis*), we assigned mass by averaging the masses of all possible species, based on range maps. Red squirrels (*Tamiasciurus hudsonicus*) were present at a single site within out study area; when unable to distinguish between the two members of the genus *Tamiasciurus* we assigned the item to the more common *T. douglasii*. Unidentified items were assigned mass by averaging the masses of the identified species in that size category and taxonomic class. <!-- does this need an example? --> As very few items could be successfully aged, we did not include prey age in our analysis. 

Data from prey remains and egested pellets are known to be biased indices of diet. <!-- citation needed --> Some authors have found combining data from both sources to produce relatively unbiased results that can serve as a helpful supplement to camera data (Lewis et al. 2004). However, after testing for differences between pooled pellets-and-remains and camera data we found significant differences between these two sources. We therefore report results from pellets and pooled pellets-and-remains separately. We do not report results from prey remains alone, as these are highly biased and rarely used in raptor diet studies.

Nest camera photos were reviewed and each new prey item delivered to the nest was recorded and identified to species when possible. When items could not be identified to species, they were identified to the lowest possible taxonomic level. Prey items identified from photos were assigned a size category and biomass by the same method used for remains and pellets. Partial items were assigned the average mass for that size category and taxonomic class. 

For the overall study area, we quantified goshawk diet in several ways using data from pellets, pooled pellets-and-remains, and nest cameras. We calculated the relative proportion of avian and mammalian biomass delivered to nests. We also calculated the relative proportion of biomass composed of tree squirrels (genus *Tamiasciurus*), which are known to be an important source of prey for goshawks in British Columbia (Ethier 1999, Lewis et al. 2006). For sites with nest cameras, we also quantified diet at the individual nest level, and further calculated diet diversity with Simpson's Diversity Index (Simpson 1949<!-- actually read this-->) and overlap between nests with Morisita's Index of Similarity (Krebs 1999), using counts of items identified to genus or better.

Sites were classified as either coastal or transition based on whether the site centroid fell within the transition zone defined by NGRT (2008). We determined the site centroid by locating the central point between all known nests within each site. Using data from pellets, pooled pellets-and-remains, and nest cameras, we quantified the diet of each zone in the same manner as for the overall study area. 

### Statistical Analysis

For ease of comparison between coastal and transition zone sites, we simplified prey items identified from nest cameras, pellets, and pooled pellets-and-remains into eight broad categories: squirrels (genus *Tamiasciurus*), hares (genus *Lepus*), all other mammals, grouse (subfamily Tetraoninae), thrushes (family Turdidae), corvids (family Corvidae), all other birds, and unidentified items. We pooled all data within each source (cameras, pellets, and pellets-and-remains) and within each zone (coastal and transition) and tested for differences between the zones with a chi-squared test using proportional counts of items.

To determine the reproductive consequences of dietary variation, we examined how two aspects of diet, diet diversity and proportion of biomass composed of squirrel, influenced productivity. We used linear regressions (lme package in R citation) with productivity as the response variable and diet as the explanatory variable. Because productivity data were only available from sites with nest cameras and nest-level diet data from pellets and prey remains were sparse, we performed this analysis using only diet data from nest cameras.