---
title: "Chapter One: Introduction 0.5"
output: html_notebook
always_allow_html: true
bibliography: chapter-one.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE)
```

Effective wildlife conservation requires understanding diet composition and its consequences for population demographics<!-- (Lourenço et al 2015) actually a statement about individual fitness, need to fix -->. Specialist predators selectively consume a narrow range of prey species regardless of their abundance, whereas generalists opportunistically consume a wider range and readily switch between species in response to changes in prey abundance (Steenhof & Kochert 1988, Terraube & Arroyo 2011). Specialization increases foraging efficiency on the preferred prey at the potential cost of decreased reproductive success <!-- output? --> for the specialist when that prey is scarce (Newton 1998<!-- check this citation -->). However, even in a generalist predator a single key prey species may be a major driver of reproductive success (Elmhagen et al 2000, Resano-Major et al 2016). For at-risk predators, increasing the abundance of key prey species may be a useful conservation tool (Ferrer & Negro 2004, Forsman et al 2004, Resano-Major et al 2016).

<!-- Elmhagen et al. 2000: "The arctic fox thus manages to combine an opportunistic feeding strategy which ensures survival in a low productivity habitat, with a remarkable ability to exploit lemming peaks for a large reproductive output." -->

<!--Resano-Major et al 2016: "We found that several key demographic parameters of an endangered raptor such as Bonelli’s eagle in western Europe are dependent on the consumption of preferred and alternative prey species and on diet diversity." -->

<!--Lourenço et al. 2015: "As dietary studies are very common in vertebrate predators, which are often threatened species, understanding how diet composition is related to other individual characteristics (e.g., home range behaviour) and their associated fitness represents a useful tool in ecology and conservation." -->

The northern goshawk (*Accipiter gentilis*) is a large forest-dwelling raptor with a Holarctic distribution. A generalist predator, the goshawk hunts a variety of small- and medium-sized mammals and birds, including squirrels, lagomorphs, grouse, corvids, and woodpeckers (Birds of the World). Despite this diverse diet, throughout much of the goshawk's range a single prey species or narrow suite of species has a strong effect on demographics. In the Yukon, goshawks depend on snowshoe hare (*Lepus americanus*) and show strong variation in productivity, mortality, and space use in response to cyclical changes in hare abundance [@doyle_population_1994]. Goshawks in Scandinavia <!-- Fennoscandia? --> likewise rely heavily on a single prey taxa, grouse (subfamily Tetraoninae), and show changes in productivity and occupancy based on annual grouse abundance [@tornberg_delayed_2005]. In contrast, goshawks in the American Southwest have a wide prey base, regularly taking some fourteen different species (Reynolds et al 1992). Fluctuations in goshawk productivity in this region are small and driven by total prey abundance, though the most influential single species is red squirrel (*Tamiasciurus hudsonicus*) [@salafsky_reproductive_2007]. These examples suggest the presence, identity, and influence of a key prey species on reproductive success in a predator as adaptable as the goshawk may be specific to each population.

Like many raptors, goshawk populations appear to be limited primarily by nest site availability and prey abundance [@reynolds_review_2006; @rutz_population_2006]. Multiple studies have documented the link between prey abundance and goshawk productivity (see these and these), and supplemental feeding has been shown to decrease nest predation, suggesting low prey abundance increases the risk of reproductive failure (Ward & Kennedy 1996). However, measuring prey abundance is not always possible and estimates may be misleading under some circumstances, such as when prey abundance does not reflect prey availability (Janes 1984,<!-- actually read this paper --> Beier & Drennan 1997<!--Ontiveros et al 2005-->) or when predators show a functional rather than numeric response to changes in prey abundance (Dupuy et al 2009). In these cases, diet variables such as composition or diversity may offer insight into factors limiting reproductive success. <!-- Optimal foraging theory predicts predators will specialize on the most profitable prey while it is abundant, and increase use of less profitable prey as its abundance decreases. This an increase in diet diversity may indicate a decrease in preferred prey abundance. -->

In British Columbia, the coastal population of northern goshawks is the subject of federal and provincial management which focuses on the protection of breeding habitat to increase nest site availability (COSEWIC 2013). This strategy is due, in part, to a relative paucity of knowledge regarding goshawk foraging behavior and habitat. Goshawks in this region are known to consume a diverse range of birds and small mammals, but their diet has not been well quantified (but see Ethier 1999). 

There is also little known about variation in diet in response to landscape characteristics. The consequences of such habitat-driven variation in diet may have significant–-or negligible-–effects on goshawk productivity and site occupancy. Here we describe goshawk diet at the nest during the breeding season and evaluate whether dietary variation affects reproductive success. <!-- the impact of nest site availability is well understood, but the impact of prey abundance is not -->

<!-- Here we describe goshawk diet at the nest during the breeding season. We evaluate whether landscape characteristics are correlated with variation in breeding season diet across this ecologically diverse region. Finally, we explore whether territory quality and reproductive success vary with diet and landscape characteristics. Addressing these fundamental knowledge gaps will assist in improving existing forest management strategies. -->

<!-- Like many raptors, goshawks appear to be limited primarily by nest site availability and food availability [@reynolds_review_2006; @rutz_population_2006]. For this reason, longstanding guidelines in the American Southwest suggest managing forests for both goshawks and goshawk prey [@reynolds_management_1992]. Under this plan, the majority of managed forest is recommended to remain in the older age classes preferred by goshawks for nesting and foraging. However, a portion should be managed as a mosaic of differently-aged stands and small gaps for the benefit of goshawk prey species. This approach remains controversial [@greenwald_review_2005], but by manipulating the amount and character of forest habitat managers seek to affect occupancy and productivity, two key drivers of breeding density. swap this out, since this chapter no longer focuses on landscape? --> 