---
title: "Chapter One: Results 0.2"
output: html_notebook
always_allow_html: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE)
```

### Diet

We obtained 26577 photos from 6 nests during the 2019 breeding season and n photos from n nests during 2020. A total of n prey item deliveries were recorded (2019 *n* = n, 2020 *n* = n). Camera effectiveness varied between sites: an average of n items were recorded per site, but some sites had as few as n items and some as many as n. Variability in effectiveness was due to differences in camera placement and sensitivity settings. n% of deliveries were obscured from the camera during delivery and consumption and were removed from the analysis. Out of the n visible items, n were identified to class and n to genus or better. Small and medium birds were disproportionately represented among items only identified to class, frequently arriving at the nest already plucked and decapitated.

Across the entire study area, we observed 16 different prey species on nest cameras (see table). By biomass, mammals made up the largest proportion of prey (84%) which was driven by the overwhelming dominance of tree squirrels (*Tamiasciurus* spp.). Birds accounted for only 13% of biomass, and the remaining 3% could not be identified to class. The most commonly identified prey categories by biomass were squirrel (71%), other mammals (7%) and thrushes (1%). Squirrels made up a large proportion of biomass delivered to each nest, but the amount was variable. Mean proportion squirrel biomass was x (sd = n). 

Based on items identified to genus or better, overall diet diversity for the study area was moderate (x = 0.53). Diet diversity of individual nests was highly variable (mean = 0.56, sd = n) and overlap between nests was low (mean = 0.26, sd = n).

Pellets and prey remains were collected from n sites in 2019 and n sites in 2020. A total of n prey items were identified from pellets. 48% of items could be identified to genus or better, and no item could not be identified at least to class. Another 68 items were identified from prey remains. 49% were identified to genus or better, and only one item could not be identified to class. From the combined pellets-and-remains sample a total of 18 unique prey species were identified.

Data from pellets showed a similar pattern to data from nest cameras, with the majority of the diet composed of mammals (77%). Squirrels made up 53% of biomass, while other birds made up another 23%. The remainder was composed of other mammals (%) and thrushes (%). The combined pellets-and-remains sample showed a very different pattern, with only 37% of the diet made up of mammals and the majority (61%) made up of birds. The most commonly identified prey group was other birds (53%), followed by squirrels (14%) and other mammals (7%).

### Difference between ecological regions

Nests in the transition zone (*n* = 4) received a slightly larger proportion of biomass from mammalian prey than did nests in the coastal zone (*n* = 2) (85% and 79%, respectively). However, the proportion of diet comprised of squirrels was equally high in both the transition zone (70%) and coastal zone (73%). Diet diversity was slightly higher in the transition zone (0.58) than the coastal zone (0.40), Mammalian prey in particular was much more diverse in the transition zone (0.45) than coastal (0.13).

Based on eight categories of prey, a chi-squared test of camera data showed a significant difference between goshawk diet in the coastal and transition zones (chi-squared = 19.725, p = 0.007). The largest difference between the zones lay in the proportion of thrushes, which was much higher in the coastal zone than expected, and in other mammals, which was much lower in the coastal zone than expected. There was no significant difference in proportion of squirrels between the two zones.

Chi-squared test of pooled pellet-and-remains data likewise showed significant differences between the two zones (chi-squared = 12.656, p = 0.04). However, a test of the pellet data alone did not show a significant difference (X = 1.9778, p = 0.66).

### Productivity

We observed no nest abandonment following camera installation. One nest in 2019 and one in 2020 failed 9 and n days after installation, respectively. The remaining n nests all fledged at least one chick. Successful nests fledged 1 (*n* = n), 2 (*n* = n), or 3 (*n* = n) chicks.

<!-- Productivity difference between years? -->

The unsuccessful 2019 nest failed after two chicks succumbed to siblicide and the third appeared to fledge prematurely. The unsuccessful 2020 nest... who knows? Siblicide was observed in two other nests, which lost one chick each.

We found no significant difference in goshawk productivity between the coastal and transitional zones (p = 0.63), nor did we find a significant effect of diet diversity on goshawk productivity (p = 0.16). However, we did find a significant effect of the proportion of diet composed of squirrels (*p* = 0.03, adjusted r^2^ = 0.64).