---
title: "Chapter One: Introduction 0.3"
output: html_notebook
always_allow_html: true
bibliography: chapter-one.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE)
```

Effective wildlife conservation requires an understanding of diet composition and its consequences for population demographics (Lourenço et al 2015) <!-- actually a statement about individual fitness, need to fix -->. Specialist predators selectively consume a narrow range of prey species regardless of their abundance, whereas generalists opportunistically consume a broader range and readily switch between species in response to changes in prey abundance (Steenhof & Kochert 1988, Terraube & Arroyo 2011). Specialization increases foraging efficiency on the preferred prey, but at the potential cost of decreased reproductive success <!-- output? --> for the specialist when that prey is scarce (Newton 1998<!-- check this citation -->). However, even in a generalist predator a single key prey species may be the primary driver of population demographics (Elmhagen et al 2000, Resano-Major et al 2016)

<!-- The arctic fox thus manages to combine an opportunistic feeding strategy which ensures survival in a low productivity habitat, with a remarkable ability to exploit lemming peaks for a large reproductive output.-->

<!--Resano-Major et al 2016: "We found that several key demographic parameters of an endangered raptor such as Bonelli’s eagle in western Europe are dependent on the consumption of preferred and alternative prey species and on diet diversity." -->

<!--Lourenço et al. 2015: "As dietary studies are very common in vertebrate predators, which are often threatened species, understanding how diet composition is related to other individual characteristics (e.g., home range behaviour) and their associated fitness represents a useful tool in ecology and conservation." -->

Generalist predators are less sensitive to fluctuations in prey abundance than specialists, as their broad diet reduces the likelihood that prey species will fluctuate synchronously. Their ability to switch between alternate prey species when one becomes rare increases population stability and decreases the risk of population decline. Despite this flexibility, a single key prey species or limited suite of species may still have a major influence on productivity, site occupancy, and other demographic drivers.

The northern goshawk (*Accipiter gentilis*) is a forest-dwelling raptor with a wide distribution and generalist diet. However, the number and identity of key prey species varies across its range, with consequences for demographic parameters. In the Yukon, goshawks depend on snowshoe hare (*Lepus americanus*) and show strong variation in productivity, mortality, and space use in response to cyclical changes in hare abundance [@doyle_population_1994]. Goshawks in Scandinavia <!-- Fennoscandia? --> likewise rely heavily on a single narrow prey group, grouse (subfamily Tetraoninae), and show changes in productivity and occupancy based on grouse abundance [@tornberg_delayed_2005]. In contrast, goshawks in the American Southwest have a wide prey base, regularly taking some fourteen different species. Population fluctuations are small and driven by total prey abundance, though the most influential single species is red squirrel (*Tamiasciurus hudsonicus*) [@salafsky_reproductive_2007]. For such an adaptable predator, the identity and influence of key prey species on population demographics may be specific to each population.

Like many raptors, goshawks in both Europe and North America appear to be limited primarily by nest site availability and food availability [@reynolds_review_2006; @rutz_population_2006]. For this reason, longstanding guidelines in the American Southwest suggest managing forests for both goshawks and goshawk prey [@reynolds_management_1992]. Under this plan, the majority of managed forest is recommended to remain in the older age classes preferred by goshawks for nesting and foraging. However, a portion should be managed as a mosaic of differently-aged stands and small gaps for the benefit of goshawk prey species. This approach remains controversial [@greenwald_review_2005], but by manipulating the amount and character of forest habitat managers seek to affect occupancy and productivity, two key drivers of breeding density. <!-- swap this out, since this chapter no longer focuses on landscape? -->

In British Columbia, the coastal population of northern goshawks is the object of federal and provincial management that focuses on the protection of nesting habitat. This strategy is due, in part, to a lack of knowledge regarding goshawk foraging behavior and foraging habitat requirements. Goshawks in this region are known to consume a diverse range of birds and small mammals, but their diet has never been quantified. There is also little known about variation in diet in response to landscape characteristics. The consequences of such habitat-driven variation in diet may have significant–-or negligible-–effects on goshawk productivity and site occupancy. Here we describe goshawk diet at the nest during the breeding season and evaluate whether dietary variation affects reproductive success.

<!-- Here we describe goshawk diet at the nest during the breeding season. We evaluate whether landscape characteristics are correlated with variation in breeding season diet across this ecologically diverse region. Finally, we explore whether territory quality and reproductive success vary with diet and landscape characteristics. Addressing these fundamental knowledge gaps will assist in improving existing forest management strategies. -->