---
title: "Chapter One: Introduction 0.6"
output: html_notebook
always_allow_html: true
bibliography: chapter-one.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE)
```

Effective wildlife conservation requires understanding diet composition and its consequences for population demographics. Specialist predators selectively consume a narrow range of prey species regardless of their abundance, whereas generalists opportunistically consume a wider range and readily switch between species in response to changes in prey abundance (Steenhof & Kochert 1988, Terraube & Arroyo 2011). Specialization increases foraging efficiency on the preferred prey at the potential cost of decreased reproductive success <!-- output? --> for the specialist when that prey is scarce (Newton 1998)<!-- check this citation -->). However, even in a generalist predator a single key prey species may be a major driver of reproductive success (Elmhagen et al 2000, Resano-Major et al 2016). For at-risk predators, increasing the abundance of key prey species may be a useful conservation tool (Ferrer & Negro 2004, Forsman et al 2004, Resano-Major et al 2016).

<!-- Elmhagen et al. 2000: "The arctic fox thus manages to combine an opportunistic feeding strategy which ensures survival in a low productivity habitat, with a remarkable ability to exploit lemming peaks for a large reproductive output." -->

<!--Resano-Major et al 2016: "We found that several key demographic parameters of an endangered raptor such as Bonelli’s eagle in western Europe are dependent on the consumption of preferred and alternative prey species and on diet diversity." -->

The northern goshawk (*Accipiter gentilis*) is a large forest-dwelling raptor with a Holarctic distribution. A generalist predator, the goshawk hunts a variety of small- and medium-sized mammals and birds, including squirrels, lagomorphs, grouse, corvids, and woodpeckers (Birds of the World). Despite this diverse diet, throughout much of the goshawk's range a single prey species or narrow suite of species has a strong effect on demographics. In the Yukon, goshawks depend on snowshoe hare (*Lepus americanus*) and show strong variation in productivity, mortality, and space use in response to cyclical changes in hare abundance [@doyle_population_1994]. Goshawks in Scandinavia <!-- Fennoscandia? --> likewise rely heavily on a single prey taxa, grouse (subfamily Tetraoninae), and show changes in productivity and occupancy based on annual grouse abundance [@tornberg_delayed_2005]. In contrast, goshawks in the American Southwest have a wide prey base, regularly taking some fourteen different species (Reynolds et al 1992)<!-- fix this, see citations in Rogers -->. Fluctuations in goshawk productivity in this region are small and driven by total prey abundance, though the most influential single species is red squirrel (*Tamiasciurus hudsonicus*) [@salafsky_reproductive_2007]. These examples suggest the presence, identity, and influence of a key prey species on reproductive success in a predator as adaptable as the goshawk may be specific to each region.

Like many raptors, goshawk populations appear to be limited primarily by nest site availability and prey abundance [@reynolds_review_2006; @rutz_population_2006]. Multiple studies have documented the link between prey abundance and goshawk productivity (see these and these), and supplemental feeding has been shown to decrease nest predation, suggesting low prey abundance increases the risk of reproductive failure (Ward & Kennedy 1996). However, measuring prey abundance is not always possible and estimates may be misleading under some circumstances, such as when prey abundance does not reflect prey availability (Janes 1984,<!-- actually read this paper --> Beier & Drennan 1997<!--Ontiveros et al 2005-->) or when predators show a functional rather than numeric response to changes in prey abundance (Dupuy et al 2009). In these cases, dietary variables such as composition or diversity may offer insight into factors limiting reproductive success. <!-- Optimal foraging theory predicts predators will specialize on the most profitable prey while it is abundant, and increase use of less profitable prey as its abundance decreases. This an increase in diet diversity may indicate a decrease in preferred prey abundance. -->

In British Columbia, the coastal population of northern goshawks is the subject of federal and provincial management which focuses on the protection of breeding habitat to increase nest site availability (COSEWIC 2013). This strategy is due, in part, to a relative paucity of knowledge regarding goshawk foraging behavior and habitat. The diet of this population appears to be variable, with hawks on Vancouver Island, British Columbia, consuming primarily red squirrels (Ethier 1999), whereas hawks in the nearby regions of southeast Alaska (Lewis et al 2006) and western Washington (Bloxton 2002) take mostly medium and large birds. Even within British Columbia, a gradient of forest types from wet coastal to dry interior may produce dietary variation at moderate scales (NGRT 2008). Detailed, local information regarding the effect of goshawk diet on reproductive success within coastal British Columbia is lacking, hindering the inclusion of limiting factors beyond nest site availability into management plans for this population.

Here we describe the breeding season diet of northern goshawks in coastal British Columbia over a two-year period. We assess whether goshawk diet differs within this region between the wetter *coastal* zone and the drier *transition* zone. We further evaluate whether dietary variables (composition, diversity) influence goshawk reproductive success. <!-- the impact of nest site availability is well understood, but the impact of prey abundance is not --> <!-- to improve understanding of how food availability limits goshawk populations -->

<!-- Here we describe goshawk diet at the nest during the breeding season. We evaluate whether landscape characteristics are correlated with variation in breeding season diet across this ecologically diverse region. Finally, we explore whether territory quality and reproductive success vary with diet and landscape characteristics. Addressing these fundamental knowledge gaps will assist in improving existing forest management strategies. -->