---
title: "Chapter One: Discussion 0.3"
output: html_notebook
always_allow_html: true
bibliography: chapter-one.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE)
```

During 2019-2020 breeding seasons we used nest cameras to assess reproductive success and diet at goshawk nests on the south coast of British Columbia. We supplemented dietary data from nest cameras with egested pellets and prey remains collected from goshawk territories. Goshawks in our study area consumed a wide range of prey species, consistent with the species' generalist foraging strategy. Despite this high dietary richness, dietary diversity was relatively low, due to the dominance of a single taxa: tree squirrels of the genus *Tamiasciurus*. We found the degree of dominance of this genus, rather than dietary diversity, drove goshawk reproductive success, indicating a specialist-like reliance on a single taxa.

Goshawks show a similar pattern of regional specialization in other portions of their range. In the interior west of North America, the key goshawk prey species is almost always a mammal, usually of the family Leporidae or Sciuridae (Boal & Mannon 1994, Doyle et al 1994, DeStefano et al 2006, Miller et al 2014). However, in the coastal temperate rainforests of the Pacific Northwest, goshawk diet generally contains more birds than mammals and the key prey is usually a species of grouse (subfamily Tetraoninae) (Watson et al 1998, Thraikill et al 2000, Bloxton 2002, Lewis et al 2006). <!-- No studies have linked grouse abundance to reproductive success in the Pacific Northwest, but it has been well documented in Finland, where goshawks likewise rely on grouse. -->Goshawks in coastal British Columbia might be expected to follow this pattern, yet on Vancouver Island goshawks consume primarily red squirrels (*T. hudsonicus*), with this single species making up x% of the diet (Ethier 1999). Similarly, we found tree squirrels (*T. douglasii* and *T. hudsonicus*) to make up, on average, x% of goshawk diet on the mainland coast.

A likely explanation for this surprising result rises from the predictions of optimal foraging theory. Predators are expected to specialize on a preferred high-value prey while its abundance is high, and diversify to less preferred prey as abundance declines (Pyke 1977<!--actually read this-->). Raptors are generally able to handle mammalian prey faster and more efficiently than avian prey (Slagsvold & Sonerud 2007, Slagsvold et al 2010). Of the potential mammalian prey present within our study area, tree squirrels' numerical density and diurnal activity pattern make them one of the most abundant and available. However, densities of tree squirrels elsewhere in the Pacific Northwest are much lower than in coastal British Columbia (Carey et al. 1992, Carey 1995, Ransome & Sullivan 2003, but see Smith 2012<!--should I really include this?-->), potentially forcing goshawks to diversify to lower-value grouse and other birds in these areas. The south coast of British Columbia and east coast of Vancouver Island lie within the rainshadow of Vancouver Island, making it slightly drier than elsewhere in the temperate rainforest zone (Meidinger & Pojar 1991). <!-- which is reflected in the patchy occurrence of tree species such as Garry's oak (*Quercus garryana*), arbutus (*Arbutus menziesii*), and pine (*Pinus sp.*).--> The unique climate of our study area may support an unusually high abundance of tree squirrels relative to other parts of the coastal Pacific Northwest, allowing goshawks to specialize on this high-value prey taxa.

Although goshawks in our study area consumed more than 16 different prey species, it was the degree of specialization on this single taxa which predicted goshawk productivity. Nests which received a greater proportion of their diet from tree squirrels fledged more chicks than those which received relatively more biomass from birds and other mammals. We observed a slight negative correlation between the proportion of diet composed of squirrel biomass <!--this isn't in methods/results, should it be? --> and diet diversity, although diversity had no significant effect on reproductive success. This suggests goshawks without access to abundant tree squirrels unsuccessfully attempted to compensate by switching to alternate prey species. Another explanation may be younger hawks lacked the experience to hunt tree squirrels regardless of squirrel abundance. Both possibilities indicate tree squirrels are one of the few taxa able to provide sufficient biomass to affect goshawk productivity. However, productivity is determined by more than fledging success alone, and additional factors such as clutch size and hatch success also play an important role (Ricklefs & Bloom 1977). Because we measured only fledging success we are unable, from the limited scope of our study, to untangle the mechanism behind this correlation.

Within our study area, low-elevation mountain valleys bridge the wet forests of the coast and the dry forests of the interior, creating a narrow region where coastal and interior goshawk populations may overlap (NGRT 2008). This transition zone provided us with a fortuitous opportunity to examine dietary variation over intermediate scales. Just as our study area is slightly drier than other regions of the coastal Pacific Northwest, the transition zone is slightly drier than the majority of our study area. <!--Other authors have speculated the dominance of avian prey in the diet of coastal Pacific Northwest goshawks is due to lower abundance or availability of mammalian prey in temperate rainforest ecosystems (Rutz et al 2006, McClaren et al 2015). -->We might therefore expect hawks in the transition zone to consume more or more variety of mammalian prey than hawks in the coastal zone. We did find a significant difference in diet between the transition and coastal zones, with hawks in the transition zone consuming a more diverse diet with a greater proportion of mammalian prey, but we found no difference in either the consumption of tree squirrels or in goshawk productivity. This similarity between ecological zones supports the conclusion that, although goshawks may opportunistically hunt prey species which are locally available, they specialize on a single high-value prey resource which strongly influences their reproductive success.

Several sources of bias complicate our conclusions, the greatest of which stems from the source of diet data. We used three sources of data to quantify goshawk diet--egested pellets, prey remains, and nest cameras--and found significant differences between the results they produced. Cameras are widely considered one of the least biased methods for measuring diet at the nest in raptors (Tornberg & Reif 2007, Garcia-Salgado et al 2015, Harrison et al 2019). We therefore consider our results from the nest cameras to be the truest approximation of goshawk diet, although we acknowledge that cameras are not entirely free of bias. Compared to cameras, prey remains were the most biased, grossly overestimating the proportion of the diet composed of avian prey. For this reasons we did not analyze prey remains alone, but the bias carried into the pooled pellets-and-remains sample, which we did analyze. On the other hand, pellets allowed few prey items to be identified to species, while prey remains allowed the identification of a large number of species, including several--primarily birds--not captured by cameras. These complex and contradictory results highlight the importance of clearly reporting the source of raptor diet data. Because each of these sources has been used in past diet studies, we believe there is value in reporting the results of each for ease of comparison. However, we recommend future diet studies prioritize collecting data via cameras, either video or still images, rather than physical specimens. 

Our study answers several fundamental questions regarding the basic ecology of an at-risk population of northern goshawks, but many more remain unanswered. We were unable to collect data on prey abundance and so cannot draw any conclusions regarding goshawk prey selection. Furthermore, while nest cameras are an effective way to measure prey delivered to the nest, they cannot record prey consumed by adults away from the nest, prey consumed by juveniles after they have fledged, or prey consumed during the winter. As a result, we captured an incomplete picture of breeding season diet and have no insight into nonbreeding season diet. These limitations are not exclusive to our work: few studies have successfully combined prey abundance with both goshawk diet and reproductive success, and no North American study has comprehensively addressed goshawk diet away from the nest (Rutz et al 2006, Squires & Kennedy 2006). Filling these gaps represents an important direction for future studies of northern goshawks in British Columbia and throughout the species' range.