---
title: "Chapter One 0.2"
output: word_document
always_allow_html: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE)
```

The development of effective conservation strategies requires a thorough understanding of the factors which limit wildlife populations. Extrinsic, or density-independent, limiting factors include weather, food availability, competitors, and human disturbance. Their effects on population density are mediated by intrinsic, or density-dependent, factors. 

In raptors, nest-site availability and food availability are common principal limiting factors. (Interactions--which is limiting and to what degree can depend on additional factors.)

The northern goshawk is a forest-dwelling raptor with a generalist diet. (Some NOGO biology, dependence on forest for nesting but variation in foraging habitat selection, productivity, dispersal, etc may be linked to locally available prey).

In British Columbia, the coastal population of northern goshawks is the focus of federal and provincial management efforts. (Lack of foraging management, need for diet info to fill knowledge gaps.) While goshawks in this region are known to consume a wide range of birds and small mammals, their diet has never been quantified. One objective of this study was therefore to quantify goshawk diet at the nest during the breeding season. Furthermore, there is no information on how goshawk diet changes at small and large scales in response to different habitat types across this ecologically diverse region. A second objective was therefore to identify which landscape characteristics are correlated with variation in breeding season diet. Finally, the consequences of habitat-driven variation in goshawk diet may have a significant--or a negligible--affect on goshawk productivity. The third objective was therefore to determine whether occupancy and reproductive success vary with diet and landscape characteristics.