---
title: "Chapter One: Introduction 0.3"
output: html_notebook
always_allow_html: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE)
```

The development of effective wildlife conservation strategies requires an understanding of diet and its consequences for population demographics. Predators with a narrow, specialized diet are sensitive to fluctuations in prey abundance. As a result, they are more vulnerable to population declines than a generalist. The broad, diverse diet of a generalist predator reduces the likelihood that prey species abundance will fluctuate synchronously. This increases the predator's opportunities to switch between alternate prey species when one becomes rare. Despite this flexibility, a single key prey species or limited suite of species may still act as the primary driver of productivity, site occupancy, and other demographic parameters.

The northern goshawk is a forest-dwelling raptor with a wide geographic range and a generalist diet. In North America they are associated with mature, closed-canopy coniferous forest. These forest characteristics are thought to increase prey availability, as goshawks appear to select foraging habitat based on the availability, rather than the abundance, of prey. However, the number and identity of key prey species varies across the goshawk's range, with consequences for foraging habitat selection, productivity, dispersal, and more. In the Yukon, goshawks are primarily dependent on snowshoe hare (*Lepus americanus*) and show strong variations in productivity, space use, and dispersal in response to cyclical variations in hare abundance. Goshawks in Scandinavia <!-- Fennoscandia? --> likewise rely heavily on a single narrow prey group, grouse (subfamily Tetraoninae), and show changes in productivity and occupancy based on grouse abundance. In contrast, goshawks in the American Southwest have a wide prey base, regularly taking some fourteen different species. Population fluctuations are small and driven by total prey abundance, but are strongly influenced by the abundance of red squirrel (*Tamiasciurus hudsonicus*). For such a adaptable predator, the identity and influence of key prey species on population demographics may be highly specific to each population.

Where populations are food-limited, incorporating prey abundance or availability into management plans may prove an effective strategy. Raptor populations are commonly food-limited, and goshawks in both Europe and North America appear to be limited primarily by food availability and nest site availability. For this reason, longstanding guidelines for the American Southwest suggest managing forests for both goshawks and goshawk prey. Under this plan, the majority of managed forest is recommended to remain in the older age classes preferred by goshawks for nesting and foraging. However, a portion should be managed as a mosaic of differently-aged stands and small gap for the benefit of goshawk prey species. This approach remains controversial, but by manipulating the amount and character of forest habitat managers seek to affect occupancy and productivity, two key drivers of breeding density.

In British Columbia, the coastal population of northern goshawks is the focus of federal and provincial management efforts. Current management strategies focus primarily on the protection of nesting habitat rather than foraging habitat. This is due to a lack of knowledge regarding goshawk foraging behavior and foraging habitat requirements. While goshawks in this regions are known to consume a wide range of birds and small mammals, their diet has never been quantified. One objective of this study was therefore to describe goshawk diet at the nest during the breeding season. Furthermore, there is no local data on how goshawk diet changes at small and large scales in response to different forest types. This region is ecologically diverse, so a second objective was to identify which landscape characteristics are correlated with variation in breeding season diet. Finally, the consequences of habitat-driven variation in goshawk diet may have a significant–-or negligible-–effect on goshawk productivity. The last objective was therefore to determine whether occupancy and reproductive success vary with diet and landscape characteristics. Addressing these fundamental knowledge gaps will assist in improving existing forest management strategies.