---
title: "Chapter One: Methods 0.1"
output: html_notebook
always_allow_html: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE)
```

### Study Area

In North America, the northern goshawk ranges from the boreal forests of the Yukon south to high-elevation forests of Arizona and New Mexico. Two subspecies are currently recognized: the widespread *atricapillus* and the limited *laingi*. The *laingi* subspecies was first described on the island of Haida Gwaii and is generally smaller in size and darker in plumage than the *atricapillus* found elsewhere on the continent. It's range, as described by morphological and genetic studies, is limited to the west coast of North America from southeast Alaska through British Columbia and Vancouver Island, and possibly as far south as Washington's Olympic Peninsula. *A. g. laingi* is designated as Threatened by the Committee on the Status of Endangered Wildlife in Canada and is on the British Columbia Red List.

We studied goshawks in the Lower Mainland and Sunshine Coast regions of the southern British Columbia coast. This coastal population is currently classified as *A. g. laingi*, though recent genetic evidence which suggests this subspecies may be limited to Haida Gwaii may lead to future reclassification. The south coast region is primarily temperate rainforest dominated by Douglas-fir (*Pseudotsuga menziesii*), western redcedar (*Thuja plicata*), and western hemlock (*Tsuga heterophylla*). Summers are cool (mean temp) and winters are mild and wet (mean temp, mean precip). Forests are naturally fragmented by mountain ranges and coastal fjords, and artificially fragmented by human development and natural resource extraction. Industrial timber harvest has created a patchwork of differently aged forest stands, ranging from recent clearcuts to old growth over two hundred years old. <!-- check this age --> Within this region, goshawk managers have delineated a *transition zone* comprised of low-elevation valleys connecting the wet coast with the dry interior. Goshawks in this transition zone may have morphological characteristics and habitat requirements intermediate between the coastal *laingi* population and the interior *atricapillus* population. As a result, this zone is of particular interest to goshawk managers.

### Data Collection

Goshawk nests were located as part of long-term monitoring conducted by the BC Ministry of Forests, Lands, Natural Resource Operations and Rural Development (FLNRO). Beginning in 2014, <!-- check this date --> FLNRO inventory crews conducted surveys for breeding goshawks in the south coast following a standard methodology (see citation for detailed survey protocol). Sites which were known to be occupied in previous years were surveyed for active nests using visual surveys and call-playback surveys. Sites without a known history of occupancy but likely to be occupied were delineated using GIS data and systematically searched using call-playback surveys.

<!-- Needs to be something here about sites being long term, given that territories are supposed to be permanent. And about nests being more ephemeral. This would include site centroid. -->

We assessed goshawk diet in 2019 and 2020 through a combination of regurgitated pellets, prey remains, and nest cameras. Data from prey remains and regurgitated pellets are known to be heavily biased indices of diet. However, combining data from both sources has been shown to produce relatively unbiased results and can be a helpful supplement to camera data (Lewis et al. 2004). After testing for differences between pooled pellets-and-remains and camera data,  we combined pellets and remains for further analysis. Prey remains and regurgitated pellets were collected from n occupied sites (2019 n = n, 2020 n = n) with active nests. N sites had collections from both years. Prey remains and pellets were gathered from beneath active nests, from within nests after the juveniles had fledged, and from plucking posts located within the site. <!-- Need to give defined area ie home range? --> All prey remains and all pellets from a single collection location (i.e., a single nest or a single plucking post) were combined for each visit to that location into a single sample. 

At a subset of these sites (2019 n = n, 2020 n = n), cameras were installed at nests to record prey delivered to the chicks. N nests had cameras installed in both years. Nest cameras are an effective and relatively unbiased method of measuring raptor diet. However, cameras risk overestimating prey deliveries because goshawks are known to cache prey items for re-delivery to the nest at a later time, creating a potential to double-count items. Due to the discrete nature of our data, we were not able to differentiate previously cached items from new items. However, we feel the risk of double-counting items was low because most intact prey remained visible in the nest until mostly or entirely consumed. Partial items could rarely be identified beyond class and so were not included in analyses of counts. <!-- Add something about amount of caching others have found? Or save until discussion? -->. 

Nest cameras were digital trail cameras (Reconyx, UltraFire and HyperFire models) mounted 2-5 meters distant from and slightly above the nest, usually in an adjacent tree but in some cases in the same tree as the nest itself. Cameras in 2019 were programmed to take three photos one second apart when triggered by motion, and an additional one photo every thirty minutes. In 2020, cameras were programmed to take five photos one second apart when triggered by motion, and an additional one photo every twenty minutes. Installation took place during the early nestling phase (between x June and x June) and cameras were left in place until after juveniles dispersed in the fall. Camera site selection was not random but rather constrained by topography, access, and timing of discovery.

Breeding chronology was not available for most sites. At nests with cameras, chicks were aged from photos taken shortly after camera installation using a pictorial guide (Boal 1994). Hatch date and lay date were calculated from this date using known breeding chronology (Boal 1994, McClaren et al. 2015). Productivity was defined as the number of chicks to reach some number of days age (citation). <!-- is sample size clear? -->

<!-- GIS data here or later on? -->

### Diet Quantification

We reconstructed prey remains and pellets following a modification of Lewis et al. (2004). Within each sample, prey remains were identified to the lowest possible taxonomic category and the minimum number of individuals counted (i.e. 11 band-tailed pigeon primaries = 2 *Patagioenas fasciata*). Intact and broken but reassembled pellets were analyzed individually within each sample, while fragmented pellets were combined within each sample. Pellets were dissected and feathers, fur, and hard parts (bones, teeth, claws) were identified to the lowest taxonomic level. We counted the minimum number of individuals represented within the pellet or pellet collection. Items were additionally categorized by size and assigned mass as for camera data (see below).

Nest camera photos were reviewed and each new prey item delivered to the nest was recorded and identified to species when possible. When items could not be identified to species, they were identified to the lowest possible taxonomic level. Items were additionally categorized by size (small, medium, or large). <!-- include reference --> Prey items identified to species were assigned mass using data from the literature. We assigned mass to mammal species from Nagorsen (2002) and birds from Birds of World (2020). When unable to differentiate between species within a single, relatively homogeneous genus (such as *Eutamias* or *Myotis*), we assigned mass by averaging the masses of all possible species, based on range maps. Red squirrels (*Tamiasciurus hudsonicus*) were present at a single site within out study area; when unable to distinguish between the two members of the genus *Tamiasciurus*, we assigned the item to the more common *T. douglasii*. Unidentified items and partial items were assigned mass by averaging the masses of the identified species in that size and class. As very few items could be successfully aged, we did not include prey age in our analysis.

For each nest, we calculated the relative proportion of avian and mammalian biomass delivered. We also calculated the proportion of total biomass composed of squirrels (genus *Tamiasciurus*), which are known to be an important source of prey for goshawks in the Pacific Northwest (Ethier 1999; Bloxton 2002; McClaren 2005; Lewis et al. 2006). <!-- But check the McClaren citation -->. We also calculated diet diversity for items identified to genus and species using Simpson's Diversity Index and diet overlap using Morisita's Index of Similarity. <!-- Is it clear that this is counts not biomass? --> <!-- clarify what is being used for what -->

### Habitat Variables

Sites were classified as either coastal or transition based on whether the site centroid fell within the defined transition zone. We quantified landscape characteristics within four nested scales around around all sites included in the study. Three of these scales were based on a conceptual model of the goshawk territory and locally relevant estimates of each: a 60-ha post-fledging area (PFA), the area used by juveniles immediately after fledging and females during chick-rearing; a 175-ha breeding area, the core-use area of the territory; and a 3800-ha home range, used by males while foraging. The final scale was a biologically realistic estimate of the maximum distance a male typically travels from the nest while foraging, approximately 32900 ha (unpublished data).

We classified forest type using biogeoclimatic (BEC) subzones and variants, a system of ecological classification widespread in BC. BEC units capture climax vegetation, relative precipitation, and relative temperature in a concise system, but do not describe local vegetation structure. To classify vegetation structure, we used data from the BC Vegetation Resource Inventory (VRI). We simplified the VRI data <!-- ok but actually figure out how that works --> to eleven cover classes (see table). <!-- do I need to talk about the raster? I think I do --> From the VRI data we also extracted four classes of canopy cover: none (<1%), low (1-30%), moderate (31-60%), and high (>60%). <!-- Ok but actually figure out what classes to use --> <!-- Also I think I actually need to say how I picked these variables --> As a final variable, we used the suitability index developed for goshawk foraging habitat developed by Mahon et al. (2008). <!-- check that citation --> 

Using the package *landscapemetrics* in R, <!-- don't forget version --> we calculated 3 metrics describing landscape composition, <!-- proportion mature forest, proportion suitable habitat, amount canopy cover --> 3 for configuration, <!-- edge density, edge density of shrub, edge density of suitable habitat -->,  2 for aggregation, <!-- contagion of landcover, contagion of HSI --> and 4 for diversity <!-- Simpson's diversity index (forest type), Simpson's diversity index (landcover), Simpson's evenness index (landcover), patch richness density (landcover) --> for each site (see table).

### Statistical Analysis

We examined pairwise Pearson's correlation coefficients among x variables at each spatial scale. For strongly correlated variables (give number), both variables were not included in the same multivariate model.

Due to the large number of explanatory landscape variables and small number of nests with sufficient diet data <!-- do you need to weed out nests with insufficient data?? -->, we developed a set of *a priori* univariate models to examine how landscape influences 3 aspects of diet <!-- diversity, proportion squirrel, proportion mammal -->. We used Aikake's Information Criterion (AIC) to select the most informative variables (deltaAIC < 2) at each scale. <!-- Or should I be using p-values to select "significant" variables? --> Within each scale, we then tested all univariate and multivariate combinations and used AIC to rank competing models. 

To determine the reproductive consequences of dietary variation, we examined how 3 aspects of diet influenced productivity. Because two of the dietary variables were highly correlated we only one (proportion squirrel). 

<!-- Missing occupancy ~ landscape -->

A site was considered occupied if a goshawk was detected within the breeding area, <!-- is this true?--> regardless of whether breeding activity was confirmed, and unoccupied if no goshawks were observed within the breeding area. Most sites were surveyed once per breeding season, which is 70% effective in detecting active goshawk nests (Woodbridge and Hargis 2006). <!-- Check this citation and reword, almost identical to Miller 2014 --> Nests were considered active if an adult was observed brooding on the nest or if chicks were seen or heard within the nest.












