---
title: "Chapter Two: Introduction 0.4"
output: html_notebook
always_allow_html: true
---
Effective wildlife management requires understanding the basis and consequences of species' habitat selection decisions (Luck 2002). Habitat selection is a hierarchical process involving a series of decisions which assesses habitat at multiple scales (Johnson 1980, Orians & Wittenberger 1991). For example, an individual selects a home range within a landscape, a nesting area within a home range, and a particular nest site within the nesting area (Luck 2002, Johnson 1980). At each scale, the individual selects habitat that maximizes survival and reproductive success (Orians & Wittenberger 1991, Martin 1998). However, selection may be driven by a different pressure at each scale, such that the selection of a home range within a landscape may be driven by one pressure, such as abundant food resources, while the selection of a nest area within a home range may be driven by another, such as safety from predators (Chalfoun & Martin 2007). Furthermore, these different pressures may affect different components of fitness, such that decisions made at the home range scale to maximize food affect clutch size or chick weight, while decisions made at the nest area scale to maximize safety affect nest survival. Correctly identifying the appropriate scale of selection and the relevant aspect of fitness is therefore crucial to understanding habitat selection and the pressures that drive it (Pribil & Picman 1997).

<!-- Luck 2002: "Determining the traits that may influence habitat choice in species is fundamental
to developing strategies aimed at habitat protection and species conservation." -->

Habitat selection decisions may be constrained by interactions with conspecifics. In territorial species, dominant individuals may monopolize preferred, high-quality habitat and force newcomers to occupy lower-quality habitat (Fretwell & Lucas 1970). These established territory holders are often of higher quality than those they displace (Sergio & Newton 2003). As a result, a small number of high-quality territories frequently occupied by high-quality individuals can act as a "source" for the population, while low-quality territories, occupied only during periods of high population density, act as "sinks" (Newton 1991, Rodenhouse et al. 1997). This has critical implications for species of conservation concern, as changes in habitat quality in a limited area may have a substantial impact on the larger population (Ferrer & Donazar 1996).

<!-- Ferrer & Donazar 1996: "Interaction between habitat and productivity complicates any prediction of the effects of habitat descrubtion on population viability. The removal of a portion of the habitat at a good site can affect the population size not only in that habitat but also in low-quality adjacent habitat, because occupancy of sites in poor habitat may depend on surplus production of young in good habitats." -->

<!-- Sergio etal 2007: "As a result, early arrival implied access to a high-quality territory, as previously pointed out in other studies (Table 3), with consequent cascading effects on subsequent reproduction." ... "laying date was positively related to arrival date and breeding output declined significantly with arrival date." ... "The interaction of age and territory quality was also significant: high breeding output could also be achieved by young males when these had access to high-quality territories or by older males when these happened to occupy low-quality territories."-->

<!-- Sergio & Newton 2003: "Black kites occupied territories from year to year in a non-random manner, with some territories preferred and others avoided. The most preferred ones were occupied earlier each year and had higher than average breeding performance." -->

<!-- Newton 1991: "high occupancy and nest success was maintained on some nesting places over periods of 10-1 5 years, despite frequent changes in occupant" -->

The northern goshawk (*Accipiter gentilis*) is a medium-sized territorial raptor with a Holarctic distribution (Squires et al. 2020). Goshawks demonstrate habitat selection at multiple spatial scales during the breeding season, utilizing large home ranges and smaller post-fledging and nest areas within the home range. At large scales, goshawks select home ranges containing forested habitats, but forest types vary widely and home ranges may also include other habitat types, including open shrub-steppe (Younk & Bechard 1994), agricultural fields (Kenward??), and urban areas (Rutz 2006). At the scale of the post-fledging and nest areas, goshawks show an increasingly strong preference for closed-canopy forest stands containing large-diameter trees, conditions which are common in mature, late-successional forests (reviewed in Andersen et al. 2005, Squires & Kennedy 2006). In North America, the goshawk's preference for mature forest has placed it at risk of population declines due to habitat loss from industrial timber harvest, and resulted in its status as a species of conservation concern (Reynolds et al. 1992, COSEWIC 2013). The coastal population of northern goshawks in British Columbia, Canada, is the subject of federal and provincial management efforts. Current management plans focus on the protection of breeding habitat at small scales around individual nest areas (FLNR 2018), a strategy which has met with some success in other raptors (that one golden eagle paper). However, plans do not address forest management at the larger scale of the foraging area, which may affect territory quality in ways which are still poorly understood.

<!-- Andersen et al. 2005: "However, even where canopy closure around a nest area is apparently low, it is still generally higher than the surrounding portions of the stand or other nearby stands. This suggests that high-canopy closure relative to the range of available canopy closure might be more important than absolute canopy closure, at least above some minimum threshold." -->

<!-- Squires & Kennedy 2006: "Although the goshawk is considered a habitat generalist at large spatial scales and uses a wide variety of forest types, it nests in a relatively narrow range of structural conditions (Reynolds et al. 1992, Squires and Reynolds 1997). Goshawks prefer mature forests with large trees, relatively closed canopies (50–90%), and open understories." "Results from some studies suggest goshawks forage in all forest types, but appear to select forests with a high density of large trees, greater canopy cover and high canopy closure, high basal area and relatively open understories in which to hunt" -->

<!-- Daw & Destefano 2001 via Squires & Kennedy: "They found that within circles of 12-ha and 24-ha plots around nests, late forest structure was more abundant than around random points" -->

<!-- McGrath et al. 2003 via Squires & Kennedy: "They provide convincing evidence that in their study area, a core area around goshawk nests where the forest is characterized by large trees with high canopy closure and this core is surrounded by a heterogeneous landscape with forest cover types that are equally abundant." -->

While these patterns are consistent relative to the available conditions present within the landscape and the home range, they vary widely across the goshawk's geographic range and between home ranges. Habitat selection has been shown to be constrained by conspecifics in one European population (Kruger & Lindstrom 2001), but it is unclear whether densities of other populations, particularly in North America, are high enough to influence habitat selection.

Under this management strategy, correctly identifying high-quality territories for protection is crucial. However, plans do not address forest management at the larger scale of the foraging area, which may affect territory quality and, ultimately, population demographics, in ways which are still poorly understood.

Here we describe the distribution of several habitat variables, measured at four spatial scales, for goshawk territories in British Columbia, Canada. We then explore which scales best describe the relationship of these variables to one indirect and one direct measure of habitat quality. Finally, we discuss the role of different selection pressures on goshawk habitat selection and fitness.

<!--
Habitat used across the goshawk's range is highly variable, with goshawks nesting in large stands of mature conifers (Daw & DeStefano 2001), fragmented stands of aspen (Younk & Bechard 1994), and small patches of urban parkland (Rutz 2006). Habitat used for foraging is even more variable, but there is a consistent preference in both nesting and foraging habitat for closed-canopy forest stands containing large-diameter trees and open understories (reviewed in Andersen et al. 2005, Squires & Kennedy 2006). Selection for this type of forest appears strongest at small scales close to the nest and weaker within the larger foraging area (Daw & Destefano 2001, Finn et al 2002?, McGrath et al. 2003). While this pattern of habitat selection at multiple spatial scales has been widely documented for goshawks, it has rarely been linked to measures of habitat quality such as occupancy or productivity (but see Finn et al. 2002?). As a result, it is difficult to identify what selection pressures are strongest at larger scales relative to smaller scales or to understand how the results of selection affect different aspects of fitness.
-->
