---
title: "Chapter Two: Methods 0.1"
output: html_notebook
always_allow_html: true
---

Beginning in 2014, <!-- check this date --> FLNRO inventory crews conducted surveys for breeding goshawks in the south coast following a standard methodology (see citation for detailed survey protocol). Survey areas were delineated in two ways: areas where goshawks were known to have bred previously (known sites), and areas likely to hold breeding goshawks based on GIS data (areas of interest). At sites known to have been occupied previously, surveyors checked known nests for signs of current breeding activity. If no known nests were active, surveyors visually searched for new or previously undiscovered nests and conducted call-playback surveys. Within areas of interest, surveyors conducted call-playback surveys while visually searching the canopy for nests. During call-playback surveys, surveyors walked transect lines spaced approximately 200 meters apart, playing goshawk alarm calls or juvenile begging calls every 200-400 meters and focusing activity on areas of forest likely to contain breeding goshawks. 

### Territory quality

To calculate an index of territory quality, we used inventory surveys to estimate how frequently <!-- is frequency what I mean here?? --> a site was occupied by a pair of goshawks. We excluded all sites with less than two years of survey data from the analysis. A site was considered occupied if a goshawk was detected within the breeding area, regardless of whether breeding activity was confirmed, and unoccupied if no goshawks were observed within the breeding area during a survey. Goshawks show strong site fidelity and sites which are occupied once tend to remain occupied over time. However, sites which are of higher quality may be expected to be occupied more often that sites of lower quality. Our method did not attempt to account for survey effort or false negatives, and so is not a true measure of occupancy; however, it may serve as index of site quality.

### Habitat Variables

Sites were classified as either coastal or transition based on whether the site fell within the transition zone defined by the NGRT (citation). We calculated the site centroid as the central point between all known nests within that site and quantified landscape characteristics within four nested scales around each centroid. Three of these scales were based on a conceptual model of the goshawk territory and locally relevant estimates of each: a 60-ha post-fledging area (PFA), the area used by juveniles immediately after fledging and by females during chick-rearing; a 200-ha breeding area, the core-use area of the territory; and a 3800-ha home range, used by males while foraging. The final scale was a biologically realistic estimate of the maximum distance a male typically travels from the nest while foraging, approximately 32900 ha (unpublished data).

We classified forest type using biogeoclimatic (BEC) subzones and variants, a system of ecological classification commonly used in BC. BEC units capture climax vegetation, relative precipitation, and relative temperature in a concise system, but do not describe local vegetation structure. To classify vegetation structure, we used data from the BC Vegetation Resource Inventory (VRI). From the VRI data we extracted eleven land cover classes based on vegetative cover and age (see table?) to a 100-m raster grid. We also extracted four classes of canopy cover: none (<1%), low (1-30%), moderate (31-60%), and high (>60%). <!-- Ok but actually figure out what classes to use --> <!-- Also I think I actually need to say how I picked these variables --> Finally, we used the suitability index developed for goshawk foraging habitat developed by Mahon et al. (2008) and widely used in goshawk management in BC.

Using the package *landscapemetrics* in R, <!-- don't forget version --> we calculated several metrics describing landscape composition for each site: <!-- proportion mature forest, proportion suitable habitat, amount canopy cover --> 3 measuring configuration, <!-- edge density, edge density of shrub, edge density of suitable habitat --> 2 measuring aggregation, <!-- contagion of landcover, contagion of HSI --> and 4 measuring diversity <!-- Simpson's diversity index (forest type), Simpson's diversity index (landcover), Simpson's evenness index (landcover), patch richness density (landcover) -->(see table). <!-- come back and fix this later -->

We examined pairwise Pearson's correlation coefficients among x landscape variables at each spatial scale. For strongly correlated variables, both variables were not included in the same multivariate model.

<!-- Collinearity among independent variables was checked with Pearson correlations, and we avoided including highly correlated variables (r > 0.7) simultaneously in models. - Beardsell et al 2016 -->

Due to the large number of explanatory landscape variables and small number of nests with sufficient diet data, we developed a set of *a priori* univariate models to examine how landscape characteristics at multiple scales influence two aspects of diet, diversity and proportion squirrel. We selected significant variables (p < 0.05) and tested all univariate and multivariate combinations within each scale. We used Aikake's Information Criterion (AIC) to rank competing models.

<!-- We used generalized linear mixed-effects models (GLMM) with a binomial
distribution to model nest-use probability, hatching success, and nesting
success, and with a Poisson distribution to model brood size.We built a set of
candidate models describing multiple hypotheses to investigate the effect of
environmental variables on nest use, hatching success, nesting success, and
brood size. Collinearity among independent variables was checked with Pearson
correlations, and we avoided including highly correlated variables (r  0.7)
simultaneously in models (i.e. these variables were tested in alternatives
models). Distance was log transformed to improve the distribution of the
residuals, and all continuous variables were centered (x  ¯x) to simplify
calculations. Models were ranked according to Akaike’s Information Criterion
corrected for small sample size (AICc). When no single model had a strong
support (i.e. Akaike weights ,0.90), model-averaged estimates and 95% confidence
intervals (CIs) were computed with multimodel inference on the most parsimonious
models (i.e. DAICc , 4) (Burnham and Anderson 2002). Because the same nests were
visited repeatedly over the years, nest ID was added as a random effect on the
intercept in all models.We also used GLMM to model reproductive-success
parameters according to nest and territory reuse (newly occupied territory [the
reference category], new nest in a previously occupied territory, and
preexisting nest in a previously occupied territory) and included nest ID and
year as random effects. In this case, clutch size was modeled with a
zero-truncated Poisson and hatching date with a Gaussian distribution.
Relationships were considered statistically significant when the 95% CIs of the
slope excluded zero. To assess the amount of variation explained by our models,
we report the marginal R2 (for fixed effects) calculated with the method
proposed by Nakagawa and Schielzeth (2013) for mixedeffects models. -->
