---
title: "Chapter Two: Introduction 0.5"
output: 
  html_notebook:
    df_print: kable
always_allow_html: true
---
Effective wildlife management requires understanding the basis and consequences of species' habitat selection decisions (Luck 2002). Habitat selection is a hierarchical process involving a series of decisions which assesses habitat at multiple scales (Johnson 1980, Orians & Wittenberger 1991). For example, an individual selects a home range within a landscape, a nesting area within a home range, and a particular nest site within the nesting area (Luck 2002, Johnson 1980). At each scale, the individual selects habitat that maximizes survival and reproductive success (Orians & Wittenberger 1991, Martin 1998). However, selection may be driven by a different pressure at each scale, such that the selection of a home range within a landscape may be driven by one pressure, such as abundant food resources, while the selection of a nest area within a home range may be driven by another, such as safety from predators (Chalfoun & Martin 2007). Furthermore, these different pressures may affect different components of fitness, such that decisions made at the home range scale to maximize food affect clutch size or chick weight, while decisions made at the nest area scale to maximize safety affect nest survival. Correctly identifying the appropriate scale of selection and the relevant aspect of fitness is therefore crucial to understanding habitat selection and the pressures that drive it (Pribil & Picman 1997).

Habitat selection decisions may be constrained by interactions with conspecifics. In territorial species, dominant individuals may monopolize preferred, high-quality habitat and force newcomers to occupy lower-quality habitat (Fretwell & Lucas 1970). Under this model, high-quality territories are predicted to be consistently occupied and highly productive. Conversely, low-quality territories are predicted to occupied infrequently and only at high population densities, and to be relatively unproductive. As a results, a small number of high-quality territories can act as a "source" for the population, while low-quality territories act as "sinks" (Newton 1991, Rodenhouse et al. 1997). This has critical implications for species of conservation concern, as changes in habitat quality in a limited area may have a substantial impact on the larger population (Ferrer & Donazar 1996).

The northern goshawk (*Accipiter gentilis*) is a medium-sized territorial raptor with a Holarctic distribution (Squires et al. 2020). Goshawks demonstrate habitat selection at multiple spatial scales during the breeding season, utilizing large home ranges and smaller post-fledging and nest areas within the home range. At large scales, goshawks select home ranges containing forested habitats, but forest types vary widely and home ranges may also include other habitat types, including open shrub-steppe (Younk & Bechard 1994), agricultural fields (Kenward??), and urban areas (Rutz 2006). At the scale of the post-fledging and nest areas, goshawks show an increasingly strong preference for closed-canopy forest stands containing large-diameter trees, conditions which are common in mature, late-successional forests (reviewed in Andersen et al. 2005, Squires & Kennedy 2006). In North America, the goshawk's preference for mature forest has placed it at risk of population declines due to habitat loss from industrial timber harvest, and resulted in its status as a species of conservation concern (Reynolds et al. 1992, COSEWIC 2013). The coastal population of northern goshawks in British Columbia, Canada, is the subject of federal and provincial management efforts. Current management plans focus on the protection of breeding habitat at small scales around individual nest areas (FLNR 2018), a strategy which has met with some success in other raptors (that one golden eagle paper). However, plans do not address forest management at the larger scale of the foraging area, which may affect territory quality in ways which are still poorly understood. Furthermore, under this management strategy, correctly identifying high-quality territories for protection is crucial. Yet while habitat characteristics have been well-described at smaller scales, and moderately described at larger scales, they have rarely been linked to measures of quality such as occupancy or productivity.

Here we describe the distribution of several habitat variables potentially important to goshawk foraging, measured at four spatial scales, for goshawk territories in British Columbia, Canada. We then explore which scales best describe the relationship of these variables to one indirect and one direct measure of habitat quality. Finally, we discuss the role of different selection pressures on goshawk habitat selection and fitness.







