---
title: "Northern goshawk diet in southwestern British Columbia"
author: "Gwyn Case"
output: 
  bookdown::word_document2:
    reference_docx: word_styles_reference_0-3.docx 
bibliography: chapter-one.bib
csl: the-journal-of-wildlife-management.csl    

---
```{r options, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE)
#  bookdown::word_document2:
#    reference_docx: word_styles_reference_0-1.docx   
```

# Abstract

Effective wildlife conservation often requires understanding diet composition and its consequences for population demographics. We measured breeding season diet of an at-risk population of northern goshawks (*Accipiter gentilis*) in coastal British Columbia using a combination of egested pellets, prey remains, and nest camera photos. We compared diet composition across two ecological zones and assessed the impact of diet diversity and dietary specialization on goshawk productivity. Our results differed between source (pellets, remains, or cameras) and measurement (biomass or counts), highlighting the importance of clearly reporting methods in raptor diet studies. Goshawks consumed 29 different prey species but primarily consumed tree squirrels (*Tamiascuirus* spp.), with this single taxon making up 59% of the biomass delivered to nests. Diet composition differed slightly between ecological zones but dietary specialization on tree squirrels was equally high in both zones. Goshawk nests monitored with nest cameras fledged 1.4 $\pm$ 0.79 chicks. However, we found no evidence to support an effect of diet diversity or dietary specialization on variation on goshawk productivity.

# General Introduction

Once valued primarily for high timber yields, temperate rainforests of the Pacific Northwest are now managed with increased emphasis on the conservation of biodiversity [@thomas_northwest_2006]. Among the drivers of this shift are declining populations of species whose life histories depend on old-growth forests. Some of these species have been placed under federal, provincial, or state protection: among others, the marbled murrelet (*Brachyramphus marmoratus*) is protected under the Species at Risk Act in Canada [@cosewic_cosewic_2014]<!-- you have the old one from 2012 but it looks like there's a new one --> and the coastal population of the pacific marten (*Martes caurina*) is protected under the Endangered Species Act in the United States [@us_fish__wildlife_service_endangered_2020]. Management under these types of legislation is typically reactive and focuses on conserving each imperiled species on a case-by-case basis [@simberloff_flagships_1998]. This approach has been widely criticized for failing to provide management for wider ecosystems, including the very ecosystems on which the imperiled species depend [@lambeck_focal_1997]. Alternatively, focusing on the broader scales of landscapes or ecosystems should preserve the ecosystem processes and services on which wild species and humans alike depend [@franklin_preserving_1993<!-- plus something for ecosystem services-->]. Yet ecosystem-based management is itself beset by numerous practical, theoretical, and even philosophical challenges which have made it difficult to implement [@lambeck_focal_1997; @simberloff_flagships_1998].

<!-- Simberloff 1998: "It is reactive, rather than proactive, and explicitly targets species and populations, in that it specifically provides protection for species (and, in certain instances, some populations rather than entire species) that are already felt to be doomed to extinction if new action is not taken to redress their decline." -->

<!-- Lambeck 1997: "Species-based approaches have been criticized on the grounds that they do not provide whole-landscape solutions to conservation problems, that they cannot be conducted at a rate sufficient to deal with the urgency of the threats, and that they consume a disproportionate amount of conservation funding." -->

Managers have often turned to surrogate species as a solution for the dilemma posed by the single-species and ecosystem-based management debate. At the core of the surrogate species concept is the belief that the requirements or wellbeing of a single species, or a small suite of species, can stand in for the needs and health of numerous co-occurring species or entire ecosystems (Caro 2010). Numerous variations and conflicting definitions are present in the literature, but the original concept may be that of the *indicator species*. The presence and population size of an indicator species is believed to reflect ecosystem processes or the populations of other species (Landres et al. 1988). <!-- Under this model, the indicator species itself may not be of conservation concern, but is strongly correlated with species and ecosystems which are. -->Perhaps more widespread than indicator species is the *umbrella species* concept. Protections which benefit umbrella species--typically wide-ranging habitat specialists--are assumed to confer protection to co-occurring species with smaller ranges and less restrictive habitat requirements (Roberge & Angelstam 2004, Seddon & Leech 2008). A related concept is the *flagship species*, a species whose protection, like an umbrella species, confers benefit on other species, but which is selected for its charisma and ability to serve as a rallying point for conservation (Andelman & Fagan 2000). These concepts all attempt to extend the relative simplicity of single-species methods to achieve the promise of ecosystem-based management [@lambeck_focal_1997].

<!-- Roberge & Angelstam 2004: "A potentially consensual alternative could be a species whose conservation confers protection to a large number of naturally co-occurring species."

"It hinges on the assumption that providing enough space for species with large area requirements will also shelter a whole suite of species with more modest spatial needs." -->

<!-- Seddon & Leech 2008: "It has been suggested that the home range size of an umbrella species should be large in comparison to sympatric species to ensure that the habitat requirements of other co-occurring species are met." 

"Habitat specialists are considered ideal umbrella species because their area requirements may be larger than those of generalists"-->

<!-- Lambeck 1997: "The challenge then is to find an efficient means of meeting the needs of all species without studying each one individually. In order to overcome this dilemma, proponents of sing-species studies have developed the concept of umbrella species." -->
  
No species better embodies the challenges of managing forest species and ecosystems in the Pacific Northwest than the northern spotted owl (*Strix occidentalis caurina*). The spotted owl is strongly associated with old-growth temperate rainforests [@forsman_diets_2004] and has at various points been proposed as an indicator [@gutierrez_ecology_1985], an umbrella [@tracy_preserving_1994], and a flagship species<!-- () --> for this ecosystem. In the late 1980s, public outcry and litigation in the United States led to the development of a spotted owl conservation strategy concurrent with the species' listing as threatened under the Endangered Species Act [@thomas_northwest_2006]. This single-species plan rapidly expanded to include other species, particularly the marbled murrelet and several salmon stocks, and ultimately evolved into the Northwest Forest Plan. The Northwest Forest Plan remained rooted in spotted owl management, but also included protections for watersheds, monitoring of rare species, and a sustainable annual timber harvest [@dellasala_special_2006]. Not all the Northwest Forest Plan's goals have been achieved--notably, spotted owl and marbled murrelet populations have continued to decline, although at a slower rate--and some parts of the plan have been eroded under subsequent presidential administrations [@dellasala_building_2015]. Yet the Northwest Forest Plan remains a powerful example of an ecosystem-based management plan with a single species at its core.

The story of the northern goshawk (*Accipiter gentilis*) in North America parallels that of the spotted owl. Goshawks are found in boreal forests across the continent and range as far south as the high-elevation forests of the American Southwest. Two subspecies (*A. g. atricapillus* and *A. g. laingi*) are widely recognized and a third (*A. g. apache*) is acknowledged by some authors [@squires_northern_2020]. Goshawks are not associated with old-growth forest to the same degree as the spotted owl, but do show a clear preference for extensive tracts of mature forest with large-diameter trees and closed canopies [@andersen_technical_2005; @squires_northern_2006]. Like the spotted owl, goshawks have been proposed as a flagship [@sergio_ecologically_2006], an indicator<!--()-->, and an umbrella species [@ozaki_mechanistic_2006]. In the American Southwest, alarms were sounded over the impact of timber harvest on northern goshawks at the same time the Northwest Forest Plan was developing in the Pacific Northwest [@crocker-bedford_goshawk_1990]. Decades of litigation failed to result in listing the southwestern population (proposed subspecies *apache*) under the Endangered Species Act, but <!--it has been classified as a sensitive species since 1982 and--> a new management plan was eventually developed <!--under the National Forest Management Act in the 1990s -->[@peck_seeing_2000]. This single-species management plan disallowed timber harvest near known goshawk nests and required a minimum amount of mature forest within the larger home range surrounding nests [@reynolds_management_1992]. Notably, the plan also specified the inclusion of younger forest, small clearings, snags, and woody debris to provide habitat for eight important goshawk prey species. This recommendation was based on the assumption that goshawks are habitat generalists limited by the abundance, not the availability, of prey--an assumption which has been the subject of heated debate [@greenwald_review_2005; @reynolds_northern_2008]. However, by incorporating multiple species, dynamic ecosystem processes, and human use, the goshawk management plan approaches the principles of ecosystem-based management and shows its potential to scale up to a more cohesive plan in the style of the Northwest Forest Plan [@graham_sustaining_1994; @peck_seeing_2000].

In the Pacific Northwest,  naturalists described a small, dark subspecies of goshawk unique to  the coastal temperate rainforests of Haida Gwaii and Vancouver Island [@taverner_variation_1940]. The size and plumage characteristics of *A. g. laingi* may be an adaptation the dark, dense forests the subspecies inhabits [@ethier_breeding_1999]<!-- actually whaley & white --> and the agile avian prey believed to dominate its diet [@penteriani_hunting_2013; @mcclaren_science-based_2015]. The precise range of *laingi* is unclear; based on morphometrics, genetics, and ecosystem mapping, it is believed to extend along the west coast and islands of British Columbia, from Southeast Alaska south to Washington's Olympic Peninsula [@northern_goshawk_recovery_team_recovery_2008; @sonsthagen_identification_2012]. In the portion of its range within the United States the *laingi* subspecies has no additional protections, but in Canada it is designated as Threatened by the Committee on the Status of Endangered Wildlife in Canada (COSEWIC). The *laingi* subspecies is further Red-listed by the British Columbia Conservation Data Centre and is an Identified Wildlife Species under the Forest Practices Code [@cosewic_cosewic_2013]. Existing management plans call for the creation of buffers around known goshawk nests and the maintenance of a minimum amount of mature forest within the larger home range, similar to the plan from the American Southwest [@mcclaren_science-based_2015; @parks_canada_agency_recovery_2018]. However, plans do not include recommendations for providing habitat for goshawk prey species. To some extent this is due to the single-species nature of the plan, but it is also a result of several knowledge gaps. Goshawk managers have acknowledged that a landscape-scale plan would be superior to the current fine-scale plan, and ecosystem-based management has been implemented elsewhere in British Columbia, most notably the Great Bear Rainforest [@price_ecosystem-based_2009<!--but can do better-->]. Together these suggest an ecosystem-based approach incorporating the goshawk as a focal species may be possible for coastal rainforests elsewhere in British Columbia. Yet while *laingi* nesting habitat is relatively well documented, foraging behavior and habitat remain poorly understood. The knowledge gaps surrounding goshawk foraging ecology hinder current single-species and potential ecosystem-based management alike. 

<!-- Ethier 1999: "Whaley and White (1994) speculate that these combined morphological traits provide A. g. laingi with an enhanced agility for hunting and penetrating through the comparatively dense forests of Vancouver Island." -->

<!-- NGRT 2008: "However, managing A. gentilis laingi on a nest-by-nest basis is an ineffective management approach at a population scale because individuals have large breeding and winter home ranges and they build multiple nests within breeding areas throughout their lifetime. Additionally, A. gentilis laingi are difficult to detect and locating all nests within a breeding home range is virtually impossible because nests will fall out of trees over time and new nests will be constructed. The recovery team recommends addressing the management of A. gentilis laingi at a landscape or watershed level to ensure that suitable breeding, foraging, and wintering habitats exist throughout the landscape."-->

My thesis attempts to fill one knowledge gap identified by the Northern Goshawk Recovery Team (NGRT) by providing basic ecological information regarding the breeding season diet of goshawks in coastal British Columbia [@northern_goshawk_recovery_team_recovery_2008]. The following chapter describes my research quantifying goshawk diet in coastal British Columbia and investigating potential links between dietary variation and goshawk reproductive success. The final chapter summarizes my results, describes the outcome of a pilot study of goshawk space-use, and discusses the implications of both for management and future research efforts.

<!--NGRT 2008: "Knowledge gaps - diet and prey availability - 1. Breeding season diet in NC and SC regions." -->

# Literature Cited {-}