---
title: "Writing outline"
output: html_notebook
---

### Introduction

<!--- 
* Quantifying dietary niche breadth is necessary to understand population demographics and plan viable population sizes.

Species conservation plans require a comprehensive understanding of the role each species plays in an ecosystem. This includes understanding the diet of each species and how fluctuations in food availability affect survival and reproduction. Furthermore, it is important to understand the flexibility a consumer may express relative to alternative prey sources. As a result, conservation and management plans for raptors have increasingly focused on prey availability in addition to habitat structure. -- Miller et al. 2014 (Introduction)
--->


Effective wildlife management requires a thorough understanding of the many factors that can affect species' population demographics, including survival, reproduction, immigration, and emigration. All of these may be influenced by diet. For individuals, abundant food increases adult survival and the number of young produced. For populations, abundant food resources can lead to population growth and the dispersal of individuals to surrounding areas. Fluctuations in the prey base may cause corresponding flucuations in population size or growth, creating instability that must be taken into account in species management plans. However, the severity of such fluctuations depends in turn on several factors, including dietary niche breadth. Species with a narrow, specialized diet are more sensitive to changes in prey abundance than those with a wide, diverse diet, and as a result may be more vulnerable to population declines and even local extinctions.


<!--
Diet may link to population fluctuation, with narrow diet leading to strong fluctuations (Yukon) and broad diet leading to low fluctuation (Kaibab). 

The diversity of prey in their diets ultimately depends on the abundance and availability of the local bird and mammal fauna, which varies geographically. In Canada, although goshawks regularly consumed several prey species (->5), goshawk reproduction showed a strong functional response to only one species--snowshoe hare (Lepusa mericanus; Doyle and Smith 2001). In contrast, 14 species of birds and mammals regularly contributed to goshawk diets in the southwestern United States (Reynolds et al. 1992). This diet diversity may stabilize their breeding rates. --Salafsky et al. 2005 (introduction)
--->


For a generalist predator, dietary breadth may depend less on which species it is capable of hunting and more on which species are available to be hunted. Within a single species' range the diversity of available prey species may vary widely, forcing some populations to subsist on a few species while other populations have access to many. A wide prey base reduces the likelihood that prey species will fluctuate synchronously, and increases the predator's ability to switch from a less abundant prey to a more abundant one. Regional diet diversity can therefore influence population productivity and stability.


<!--
Different areas dominated by different forest types may be expected to have different prey base, with consequences for brood size and ultimately population growth.

Our predictions are as follows: 1. There should be significant landscape-related differences in the goshawk diet, suggesting differences in the availability of prey. 2. The availability of certain prey types may affect the brood size of the goshawk, suggesting their particular importance among the total amount of suitable
prey. -- Solonen et al. 2019 (Introduction)
-->


In addition to prey diversity, prey species composition may also vary across a species' range. Factors such as abundance, size, encounter rate, and handling time can make some prey species more desirable than others. The presence of these species can increase population productivity by providing an especially valuable food resource, but also decrease population stability if they are prone to fluctuations in abundance. These two factors---prey diversity and prey composition---combine to make diet a powerful influence on population demographics.


<!--
Recommendations for goshawk management include increasing prey abundance through forest management (Reynolds). This opens to the door to umbrella-style or ecosystem-based management, but that requires a thorough understanding of links between diet, prey, and landscape.

Six nonexclusive hypotheses have been proposed to explain the requirement of spotted owls for old growth, but only abundance of prey can explain the requirement of Spotted Owls for large areas of old growth (Carey 1985). This hypothesis predicts that prey abun- dance (and diversity) and landscape composition should be the major correlates of home range size and the absolute amount of old growth in the range, that latitudinal variation in home range size should reflect prey distribution with changes in home range size being abrupt (reflecting abrupt changes in prey diversity), as opposed to clinal, and that selection of foraging habitat should reflect prey abundance. -- Carey et al. 1992 (Introdution)
--->

Both factors ultimately depend on landscape characteristics. At larger scales, ecosystem type dictates the distribution of prey species, while at smaller scales, habitat type affects local patterns of abundance. The effects of small- and large-scale landscape patterns, transmitted through prey resources, can influence individual survival and productivity, and population growth and dispersal. For this reason, longstanding management recommendations for the northern goshawk in the American Southwest have called for managing the landscape for goshawk prey as well as for goshawks themselves.

The northern goshawk is a forest-dwelling raptor with a Holarctic distribution and a generalist diet. In North America, the species is associated with mature conifer forest, breeding in closed-canopy stands with large trees and limited understories. Widespread habitat loss, primarily due to timber harvest, raised concerns that the species may be declining. Management guidelines were developed by the U.S. Forest Service (USFS) which identified 14 important prey species and included recommendations to manage forests as a mosaic of differently-aged stands and small openings for their benefit.

The applicability of these guidelines to other portions of the goshawk's range is unknown. On the Kaibab platueau, where they were developed, goshawks have access to a wide prey base and fluctuations in goshawk productivity are small and driven primarily by the abundance of red squirrel (*Tamiasciurus hudsonicus*). In the Yukon, on the other hand, goshawks have a much narrower prey base and show strong variations in productivity, space use, and dispersal in response to populations of snowshoe hare (*Lepus americanus*), which are their main prey. For such a generalist predator, management guidelines, especially those which incorporate management for prey species, must take local diet into account.

In British Columbia, the coastal population of northern goshawks is the focus of federal and provincial management efforts, which currently do not include recommendations for foraging habitat management or the management of prey species. While goshawks in this region are known to consume a wide range of birds and small mammals, their diet has never been quantified. One objective of this study was therefore to quantify goshawk diet at the nest during the breeding season. Furthermore, there is no information on how goshawk diet changes at small and large scales in response to different habitat types across this ecologically diverse region. A second objective was therefore to identify which landscape characteristics are correlated with variation in breeding season diet. Finally, the consequences of habitat-driven variation in goshawk diet may have a significant--or a negligible--affect on goshawk productivity. The third objective was therefore to determine whether occupancy and reproductive success vary with diet and landscape characteristics.

<!-- Did I make the tie to occupancy and RS clear enough?? -->

### Study area

<!--
### Methods

* Identification & counting of images/collections, biomass
    * Lewis et al. 2004
    * Rogers et al 2006
* Statistics (summary of items, comparisons)
    * Lewis et al. 2006

### Results
* Summary of deliveries, delivery rate
    * Rogers et al. 2006

### Conclusions
* Different forest types provide different prey bases, with consequences for home range size and other drivers of demographics.

> Southwestern Oregon is a transition zone with the fauna reflecting both northern and southern species. Our mixed-conifer study areas were probably the area of maximum over- lap between the dusky-footed woodrat and the bushy- tailed woodrat. Our study areas are at the northern limit of the dusky-footed woodrat in upland, forested areas. In the transition zone, especially in old growth, the two species coexist (although their densities are negatively correlated); further south, it appears the bushy-tailed woodrat is confined to rock outcrops (Carey 1991). Thus, with two species of woodrats and the flying squirrel, the transition zone provides a large and diverse prey base for the owl. The amounts of old forest (454 ha) used annually by pairs in the clumped, mixed- conifer forest are the smallest ever reported for the Northern Spotted Owl. -- Carey etal. 1992

* Some prey species appear to be more important to goshawks than others. What makes a prey species more valuable is probably the result of an interaction between encounter rate, ease of capture, and size.

> The difference in theapparent influence of individual prey species is
likely a result of encounter rates with goshawks. Goshawks are opportunistsa nd will presumably attempt to capture whatever prey species are readily available. However, the limited distributions or different activity patterns of some prey species decreasest he probability that diurnal goshawks will encounter them while foraging. --Salafsky et al. 2005 (conclusion)

* Results support the importance of the mammals, especially squirrels, in the diet. This agrees with results across North America, but not with results from SE Alaska, which showed a greater proportion of birds.

> Past discrepancies among studies with respect to proportions of mammalian and avian prey items might be attributable to the method used to quantify diet. Most studies that reported a higher percent of birds than mammals in goshawk diet used indirect methods such as analysis of pellets or prey remains to assess dietary components. These methods have been scrutinized because they can overestimate bird species due to the relative ease in locating feathers over small pieces of mammal fur and bones (Simmons et al. 1991, Beilefeldt et al. 1992) -- Rogers et al. 2006 (Conclusion)

* Management recommendations in the US suggest managing forests for the direct benefit of goshawk prey, with only indirect benefits to goshawks. Our results support the idea that managing for select prey species may be beneficial. Our results also provide a locally-relevant list of species for consideration, since those recommendations come from the American SW.

> In 1992, the USDA Forest Service (USFS) developed guidelines for Northern Goshawks and forest management that are currently being implemented on some national forests across the southwestern US (Reynolds et al. 1992). These management recommendations recognized 14 consistently abundant and important prey species, out of a total of 66 potential prey species from various goshawk diet studies (Schnell 1958, Meng 1959, Reynolds and Meslow 1984, Kennedy 1991, Boal and Mannan 1994) and suggested managing habitat for all prey species. Among the 14 prey species listed in the guidelines, we observed that six species contributed >5% each
to goshawk diet on the Sitgreaves Forest. Our study supports the idea that managing habitat for these consistently hunted prey items is important. -- Rogers et al. 2006 (Conclusion)

> Management of landscapes to maintain viable populations of Spotted Owls also entails management of forest upon which prey species depend. -- Carey et al. 1992
-->