---
title: "R Notebook"
output: github_document
---

```{r options, include=FALSE}
knitr::opts_chunk$set(echo=TRUE, message=FALSE, warning=FALSE)
```

So apparently I never actually made a full notebook for my chi-squared tests.

```{r message=FALSE, warning=FALSE}
# Import conflict settings.
source('../src/conflicted.R')

#Load some libraries.
library(tidyverse)

# Bring in diet data.
source('../src/prey_attributes_revised.R')

# Add grouping variable.
diet.items <- diet.items %>% mutate(group=case_when(
  class == 'Aves' & family == 'Phasianidae' ~ 'grouse',
  class == 'Aves' & family == 'Corvidae' ~ 'corvid',
  class == 'Aves' & family == 'Turdidae' ~ 'thrush',
  class == 'Aves' ~ 'bird',
  class == 'Mammalia' & genus == 'Tamiasciurus' ~ 'squirrel',
  class == 'Mammalia' & genus == 'Lepus' ~ 'hare',
  class == 'Mammalia' ~ 'mammal',
  TRUE ~ 'unknown'
))

# Bring in zone data.
centroids <- read_csv('../data/interim/zone_centroid_sites.csv')

# Make a frequency table of groups for camera data.
freq.camera <- centroids %>% 
  select(site, zone) %>% right_join(diet.items, by=c('site')) %>% 
  filter(method == 'camera') %>%
  group_by(zone, group) %>%
  mutate(count=n()) %>% 
  select(zone, group, count) %>% 
  distinct() %>% ungroup() %>% 
  pivot_wider(names_from='group', values_from='count', values_fill=0) %>% 
  column_to_rownames(var='zone')

freq.camera
```

So far so good. Now run a chi-squared test.

```{r}
chi.camera <- chisq.test(freq.camera, correct=FALSE, simulate.p.value=TRUE)

chi.camera
```

Oh good lord, why is that a different number than I got last time?? I used the exact same code...

Ah well, still significant so...

Ok, so the distribution of prey items is different between the two zones. But *how* is it different?

```{r}
# Raw residuals.
chi.camera$residuals

# Standardized residuals.
chi.camera$stdres
```
So same results